// ============================================================
// BDD ACCENTS — verbes uniquement (é, è, ê, e sonnant [ɛ])
// inf = infinitif du verbe, affiche en aide dans les forms completes
// niveau : facile (1 position testee) / difficile (2+ positions)
// ============================================================
const verbesAccents = [
  {"mot":"préféré","inf":"préférer","cible":"é","niveau":"difficile"},
  {"mot":"préféré","inf":"préférer","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"préféré","inf":"préférer","pos":3,"cible":"é","niveau":"difficile"},
  {"mot":"elle m'intéresse","inf":"intéresser","pos":1,"cible":"é","niveau":"difficile"},
  {"mot":"elle m'intéresse","inf":"intéresser","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"elle m'étonne","inf":"étonner","cible":"é","niveau":"facile"},
  {"mot":"je répare","inf":"réparer","cible":"é","niveau":"facile"},
  {"mot":"elle présente","inf":"présenter","cible":"é","niveau":"facile"},
  {"mot":"tu t'égares","inf":"s'égarer","cible":"é","niveau":"facile"},
  {"mot":"il se décourage","inf":"se décourager","cible":"é","niveau":"facile"},
  {"mot":"je stupéfie","inf":"stupéfier","cible":"é","niveau":"facile"},
  {"mot":"j'appréhende","inf":"appréhender","cible":"é","niveau":"facile"},
  {"mot":"je me réveille","inf":"se réveiller","cible":"é","niveau":"facile"},
  {"mot":"je réfléchis","inf":"réfléchir","cible":"é","niveau":"difficile"},
  {"mot":"je réfléchis","inf":"réfléchir","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je réussis","inf":"réussir","cible":"é","niveau":"facile"},
  {"mot":"elle représente","inf":"représenter","pos":2,"cible":"é","niveau":"facile"},
  {"mot":"je vécus","inf":"vivre","cible":"é","niveau":"facile"},
  {"mot":"tu régules","inf":"réguler","cible":"é","niveau":"facile"},
  {"mot":"je préfère","inf":"préférer","cible":"é","niveau":"difficile"},
  {"mot":"elle étincelle","inf":"étinceler","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"j'apprécie","inf":"apprécier","cible":"é","niveau":"facile"},
  {"mot":"j'atténue","inf":"atténuer","cible":"é","niveau":"facile"},
  {"mot":"je bégaie","inf":"bégayer","cible":"é","altRad":"bégaye","niveau":"facile"},
  {"mot":"je bénéficie","inf":"bénéficier","cible":"é","niveau":"difficile"},
  {"mot":"je bénéficie","inf":"bénéficier","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je différencie","inf":"différencier","cible":"é","niveau":"facile"},
  {"mot":"je déblaie","inf":"déblayer","cible":"é","altRad":"déblaye","niveau":"facile"},
  {"mot":"je défraie","inf":"défrayer","cible":"é","altRad":"défraye","niveau":"facile"},
  {"mot":"je délaie","inf":"délayer","cible":"é","altRad":"délaye","niveau":"facile"},
  {"mot":"j'égaie","inf":"égayer","cible":"é","altRad":"égaye","niveau":"facile"},
  {"mot":"j'étaie","inf":"étayer","cible":"é","altRad":"étaye","niveau":"facile"},
  {"mot":"je décrie","inf":"décrier","cible":"é","niveau":"facile"},
  {"mot":"je défie","inf":"défier","cible":"é","niveau":"facile"},
  {"mot":"je délie","inf":"délier","cible":"é","niveau":"facile"},
  {"mot":"je dénie","inf":"dénier","cible":"é","niveau":"facile"},
  {"mot":"je dénoue","inf":"dénouer","cible":"é","niveau":"facile"},
  {"mot":"je déplie","inf":"déplier","cible":"é","niveau":"facile"},
  {"mot":"je déploie","inf":"déployer","cible":"é","niveau":"facile"},
  {"mot":"j'expédie","inf":"expédier","cible":"é","niveau":"facile"},
  {"mot":"j'éberlue","inf":"éberluer","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"j'épie","inf":"épier","cible":"é","niveau":"facile"},
  {"mot":"j'éternue","inf":"éternuer","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"j'étudie","inf":"étudier","cible":"é","niveau":"facile"},
  {"mot":"j'évacue","inf":"évacuer","cible":"é","niveau":"facile"},
  {"mot":"j'évalue","inf":"évaluer","cible":"é","niveau":"facile"},
  {"mot":"j'évolue","inf":"évoluer","cible":"é","niveau":"facile"},
  {"mot":"je maugrée","inf":"maugréer","cible":"é","info":"conserve l'accent aigu du radical.","niveau":"facile"},
  {"mot":"je négocie","inf":"négocier","cible":"é","niveau":"facile"},
  {"mot":"je privilégie","inf":"privilégier","cible":"é","niveau":"facile"},
  {"mot":"je recrée","inf":"recréer","pos":2,"cible":"é","info":"conserve l'accent aigu du radical.","niveau":"facile"},
  {"mot":"je crée","inf":"créer","cible":"é","info":"conserve l'accent aigu du radical.","niveau":"facile"},
  {"mot":"je remédie","inf":"remédier","cible":"é","niveau":"facile"},
  {"mot":"je réconcilie","inf":"réconcilier","pos":2,"cible":"é","niveau":"facile"},
  {"mot":"je répertorie","inf":"répertorier","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je résilie","inf":"résilier","cible":"é","niveau":"facile"},
  {"mot":"je spécifie","inf":"spécifier","cible":"é","niveau":"facile"},
  {"mot":"je supplée","inf":"suppléer","cible":"é","niveau":"facile"},
  {"mot":"je vérifie","inf":"vérifier","cible":"é","niveau":"facile"},
  {"mot":"j'obéis","inf":"obéir","cible":"é","niveau":"facile"},
  {"mot":"je guéris","inf":"guérir","cible":"é","niveau":"facile"},
  {"mot":"j'établis","inf":"établir","cible":"é","niveau":"facile"},
  {"mot":"je réagis","inf":"réagir","cible":"é","niveau":"facile"},
  {"mot":"je réunis","inf":"réunir","cible":"é","niveau":"facile"},
  {"mot":"j'élargis","inf":"élargir","cible":"é","niveau":"facile"},
  {"mot":"je gémis","inf":"gémir","cible":"é","niveau":"facile"},
  {"mot":"j'anéantis","inf":"anéantir","cible":"é","niveau":"facile"},
  {"mot":"je définis","inf":"définir","cible":"é","niveau":"facile"},
  {"mot":"je démolis","inf":"démolir","cible":"é","niveau":"facile"},
  {"mot":"je désobéis","inf":"désobéir","pos":2,"cible":"é","niveau":"facile"},
  {"mot":"j'éblouis","inf":"éblouir","cible":"é","niveau":"facile"},
  {"mot":"j'étourdis","inf":"étourdir","cible":"é","niveau":"facile"},
  {"mot":"je frémis","inf":"frémir","cible":"é","niveau":"facile"},
  {"mot":"je réjouis","inf":"réjouir","cible":"é","niveau":"facile"},
  {"mot":"je rétablis","inf":"rétablir","cible":"é","niveau":"facile"},
  {"mot":"je rétrécis","inf":"rétrécir","cible":"é","niveau":"facile"},
  {"mot":"je dépéris","inf":"dépérir","cible":"é","niveau":"difficile"},
  {"mot":"je dépéris","inf":"dépérir","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"j'épaissis","inf":"épaissir","cible":"é","niveau":"facile"},
  {"mot":"j'épanouis","inf":"épanouir","cible":"é","niveau":"facile"},
  {"mot":"je flétris","inf":"flétrir","cible":"é","niveau":"facile"},
  {"mot":"je découds","inf":"découdre","cible":"é","niveau":"facile"},
  {"mot":"je défends","inf":"défendre","cible":"é","niveau":"facile"},
  {"mot":"je démords","inf":"démordre","cible":"é","niveau":"facile"},
  {"mot":"je désapprends","inf":"désapprendre","cible":"é","niveau":"facile"},
  {"mot":"je détends","inf":"détendre","cible":"é","niveau":"facile"},
  {"mot":"je détords","inf":"détordre","cible":"é","niveau":"facile"},
  {"mot":"j'épands","inf":"épandre","cible":"é","niveau":"facile"},
  {"mot":"j'étends","inf":"étendre","cible":"é","niveau":"facile"},
  {"mot":"je prétends","inf":"prétendre","cible":"é","niveau":"facile"},
  {"mot":"je réapprends","inf":"réapprendre","cible":"é","niveau":"facile"},
  {"mot":"je réentends","inf":"réentendre","cible":"é","niveau":"facile"},
  {"mot":"je répands","inf":"répandre","cible":"é","niveau":"facile"},
  {"mot":"je réponds","inf":"répondre","cible":"é","niveau":"facile"},
  {"mot":"je débats","inf":"débattre","cible":"é","niveau":"facile"},
  {"mot":"je démets","inf":"démettre","cible":"é","niveau":"facile"},
  {"mot":"j'émets","inf":"émettre","cible":"é","niveau":"facile"},
  {"mot":"je télétransmets","inf":"télétransmettre","cible":"é","niveau":"difficile"},
  {"mot":"je télétransmets","inf":"télétransmettre","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je décris","inf":"décrire","cible":"é","niveau":"facile"},
  {"mot":"je déduis","inf":"déduire","cible":"é","niveau":"facile"},
  {"mot":"je défais","inf":"défaire","cible":"é","niveau":"facile"},
  {"mot":"je démens","inf":"démentir","cible":"é","niveau":"facile"},
  {"mot":"je dépeins","inf":"dépeindre","cible":"é","niveau":"facile"},
  {"mot":"je déteins","inf":"déteindre","cible":"é","niveau":"facile"},
  {"mot":"je détiens","inf":"détenir","cible":"é","niveau":"facile"},
  {"mot":"je détruis","inf":"détruire","cible":"é","niveau":"facile"},
  {"mot":"je méconnais","inf":"méconnaître","cible":"é","niveau":"facile"},
  {"mot":"je déplais","inf":"déplaire","cible":"é","niveau":"facile"},
  {"mot":"je préviens","inf":"prévenir","cible":"é","niveau":"facile"},
  {"mot":"je prévois","inf":"prévoir","cible":"é","niveau":"facile"},
  {"mot":"je réapparais","inf":"réapparaître","cible":"é","niveau":"facile"},
  {"mot":"elle réapparaît","inf":"réapparaître","altRad":"réapparait","cible":"é","niveau":"facile"},
  {"mot":"je récris","inf":"récrire","cible":"é","niveau":"facile"},
  {"mot":"je réinscris","inf":"réinscrire","cible":"é","niveau":"facile"},
  {"mot":"je réintroduis","inf":"réintroduire","cible":"é","niveau":"facile"},
  {"mot":"je séduis","inf":"séduire","cible":"é","niveau":"facile"},
  {"mot":"elle considère","inf":"considérer","cible":"è","niveau":"facile"},
  {"mot":"elle digère","inf":"digérer","cible":"è","niveau":"facile"},
  {"mot":"je modèle","inf":"modeler","cible":"è","niveau":"facile"},
  {"mot":"j'achète","inf":"acheter","cible":"è","niveau":"facile"},
  {"mot":"je gèle","inf":"geler","cible":"è","niveau":"facile"},
  {"mot":"je lève","inf":"lever","cible":"è","niveau":"facile"},
  {"mot":"je pèse","inf":"peser","cible":"è","niveau":"facile"},
  {"mot":"je libère","inf":"libérer","cible":"è","niveau":"facile"},
  {"mot":"je tolère","inf":"tolérer","cible":"è","niveau":"facile"},
  {"mot":"je modère","inf":"modérer","cible":"è","niveau":"facile"},
  {"mot":"je coopère","inf":"coopérer","cible":"è","niveau":"facile"},
  {"mot":"j'adhère","inf":"adhérer","cible":"è","niveau":"facile"},
  {"mot":"je transfère","inf":"transférer","cible":"è","niveau":"facile"},
  {"mot":"je prolifère","inf":"proliférer","cible":"è","niveau":"facile"},
  {"mot":"je diffère","inf":"différer","cible":"è","niveau":"facile"},
  {"mot":"j'opère","inf":"opérer","cible":"è","niveau":"facile"},
  {"mot":"j'altère","inf":"altérer","cible":"è","niveau":"facile"},
  {"mot":"je cède","inf":"céder","cible":"è","niveau":"facile"},
  {"mot":"je possède","inf":"posséder","cible":"è","niveau":"facile"},
  {"mot":"je succède","inf":"succéder","cible":"è","niveau":"facile"},
  {"mot":"je procède","inf":"procéder","cible":"è","niveau":"facile"},
  {"mot":"je concède","inf":"concéder","cible":"è","niveau":"facile"},
  {"mot":"je complète","inf":"compléter","cible":"è","niveau":"facile"},
  {"mot":"j'interprète","inf":"interpréter","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je protège","inf":"protéger","cible":"è","niveau":"facile"},
  {"mot":"j'abrège","inf":"abréger","cible":"è","niveau":"facile"},
  {"mot":"j'assiège","inf":"assiéger","cible":"è","niveau":"facile"},
  {"mot":"tu craquelles","inf":"craqueler","cible":"e","altRad":"craquèles","niveau":"difficile"},
  {"mot":"je ficelle","inf":"ficeler","cible":"e","altRad":"ficèle","niveau":"difficile"},
  {"mot":"il ficelle","inf":"ficeler","cible":"e","altRad":"ficèle","niveau":"difficile"},
  {"mot":"tu harcèles","inf":"harceler","cible":"è","niveau":"facile"},
  {"mot":"on jumelle","inf":"jumeler","cible":"e","altRad":"jumèle","niveau":"difficile"},
  {"mot":"tu craquelleras","inf":"craqueler","cible":"e","altRad":"craquèleras","niveau":"difficile"},
  {"mot":"il débossellera","inf":"débosseler","cible":"e","altRad":"débossèlera","niveau":"difficile"},
  {"mot":"ils épelleront","inf":"épeler","cible":"e","altRad":"épèleront","niveau":"difficile"},
  {"mot":"nous ficellerons","inf":"ficeler","cible":"e","altRad":"ficèlerons","niveau":"difficile"},
  {"mot":"vous harcèlerez","inf":"harceler","cible":"è","niveau":"facile"},
  {"mot":"nous jumellerons","inf":"jumeler","cible":"e","altRad":"jumèlerons","niveau":"difficile"},
  {"mot":"je protègerai","inf":"protéger","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je tolèrerai","inf":"tolérer","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je coopèrerai","inf":"coopérer","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"j'exagèrerai","inf":"exagérer","pos":2,"cible":"è","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"j'opèrerai","inf":"opérer","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je cèderai","inf":"céder","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je possèderai","inf":"posséder","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je procèderai","inf":"procéder","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je succèderai","inf":"succéder","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je complèterai","inf":"compléter","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"j'espère","inf":"espérer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"j'interfère","inf":"interférer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je chancelle","inf":"chanceler","cible":"e","altRad":"chancèle","niveau":"difficile"},
  {"mot":"je chancellerai","inf":"chanceler","cible":"e","altRad":"chancèlerai","niveau":"difficile"},
  {"mot":"j'arrête","inf":"arrêter","cible":"ê","info":"de la famille d'arrestation","niveau":"facile"},
  {"mot":"je m'entête","inf":"s'entêter","pos":2,"cible":"ê","info":"vient du latin testa","niveau":"facile"},
  {"mot":"elle fête","inf":"fêter","cible":"ê","info":"de la famille de festif","niveau":"facile"},
  {"mot":"être","inf":"être","cible":"ê","info":"de la famille de je suis, nous sommes, elles sont","niveau":"facile"},
  {"mot":"tu rêves","inf":"rêver","cible":"ê","niveau":"facile"},
  {"mot":"tu m'embêtes","inf":"embêter","pos":2,"cible":"ê","info":"de la famille de bestial, bestiaux","niveau":"facile"},
  {"mot":"il se défenêtre","inf":"se défenêtrer","pos":1,"cible":"é","niveau":"difficile"},
  {"mot":"il se défenêtre","inf":"se défenêtrer","pos":3,"cible":"ê","info":"de la famille de défenestrer","niveau":"difficile"},
  {"mot":"elle tempête","inf":"tempêter","pos":2,"cible":"ê","info":"de la famille de tempest en anglais","niveau":"facile"},
  {"mot":"il crêpe","inf":"crêper","cible":"ê","info":"vient du latin crispus","niveau":"facile"},
  {"mot":"elles viennent","inf":"venir","cible":"e","niveau":"difficile"},
  {"mot":"elles parviennent","inf":"parvenir","cible":"e","niveau":"difficile"},
  {"mot":"elles reviennent","inf":"revenir","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"elles tiennent","inf":"tenir","cible":"e","niveau":"difficile"},
  {"mot":"elles retiennent","inf":"retenir","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"elles détiennent","inf":"détenir","cible":"e","niveau":"difficile"},
  {"mot":"elles comprennent","inf":"comprendre","cible":"e","niveau":"difficile"},
  {"mot":"elles reprennent","inf":"reprendre","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"elles apprennent","inf":"apprendre","cible":"e","niveau":"difficile"},
  {"mot":"j'interprète","inf":"interpréter","cible":"e","niveau":"difficile"},
  {"mot":"j'appelle","inf":"appeler","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je rappelle","inf":"rappeler","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"j'interpelle","inf":"interpeller","cible":"e","niveau":"difficile"},
  {"mot":"j'interpelle","inf":"interpeller","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je rejette","inf":"rejeter","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je projette","inf":"projeter","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je jette","inf":"jeter","cible":"e","niveau":"difficile"},
  {"mot":"je projette","inf":"projeter","cible":"e","niveau":"difficile"},
  {"mot":"j'espère","inf":"espérer","cible":"e","niveau":"difficile"},
  {"mot":"j'interfère","inf":"interférer","cible":"e","niveau":"difficile"},
  {"mot":"j'exagèrerai","inf":"exagérer","cible":"e","altRad":"exagérerai","niveau":"difficile"},
  {"mot":"j'appelle","inf":"appeler","cible":"e","niveau":"difficile"},
  {"mot":"je rappelle","inf":"rappeler","cible":"e","niveau":"difficile"},
  {"mot":"je persévèrerai","inf":"persévérer","cible":"e","altRad":"persévérerai","niveau":"difficile"},
  {"mot":"je persévèrerai","inf":"persévérer","pos":2,"cible":"é","altRad":"persévérerai","niveau":"difficile"},
  {"mot":"je persévèrerai","inf":"persévérer","pos":3,"cible":"è","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je préférerai","inf":"préférer","cible":"é","altRad":"préfèrerai","niveau":"difficile"},
  {"mot":"je préférerai","inf":"préférer","pos":2,"cible":"é","altRad":"préfèrerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"j'accélèrerai","inf":"accélérer","cible":"é","altRad":"accélérerai","niveau":"difficile"},
  {"mot":"j'accélèrerai","inf":"accélérer","pos":2,"cible":"è","altRad":"accélérerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je récupèrerai","inf":"récupérer","cible":"é","altRad":"récupérerai","niveau":"difficile"},
  {"mot":"je récupèrerai","inf":"récupérer","pos":2,"cible":"è","altRad":"récupérerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je génèrerai","inf":"générer","cible":"é","altRad":"générerai","niveau":"difficile"},
  {"mot":"je génèrerai","inf":"générer","pos":2,"cible":"è","altRad":"générerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je répèterai","inf":"répéter","cible":"é","altRad":"répéterai","niveau":"difficile"},
  {"mot":"je répèterai","inf":"répéter","pos":2,"cible":"è","altRad":"répéterai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je réfèrerai","inf":"référer","cible":"é","altRad":"référerai","niveau":"difficile"},
  {"mot":"je réfèrerai","inf":"référer","pos":2,"cible":"è","altRad":"référerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je pénétrerai","inf":"pénétrer","cible":"é","altRad":"pénètrerai","niveau":"difficile"},
  {"mot":"je pénétrerai","inf":"pénétrer","pos":2,"cible":"é","altRad":"pénètrerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"je déléguerai","inf":"déléguer","cible":"é","altRad":"délèguerai","niveau":"difficile"},
  {"mot":"je déléguerai","inf":"déléguer","pos":2,"cible":"é","altRad":"délèguerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"j'interprèterai","inf":"interpréter","cible":"e","altRad":"interpréterai","niveau":"difficile"},
  {"mot":"j'interprèterai","inf":"interpréter","pos":2,"cible":"è","altRad":"interpréterai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"j'espèrerai","inf":"espérer","cible":"e","altRad":"espérerai","niveau":"difficile"},
  {"mot":"j'espèrerai","inf":"espérer","pos":2,"cible":"è","altRad":"espérerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je libèrerai","inf":"libérer","cible":"è","altRad":"libérerai","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"il débossellera","inf":"débosseler","cible":"é","niveau":"difficile"},
  {"mot":"j'accélérerai","inf":"accélérer","cible":"é","altRad":"accélèrerai","niveau":"difficile"},
  {"mot":"j'accélérerai","inf":"accélérer","pos":2,"cible":"é","altRad":"accélèrerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"elle répète","inf":"répéter","cible":"é","niveau":"difficile"},
  {"mot":"elle répète","inf":"répéter","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je délègue","inf":"déléguer","cible":"é","niveau":"difficile"},
  {"mot":"je délègue","inf":"déléguer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je génère","inf":"générer","cible":"é","niveau":"difficile"},
  {"mot":"je génère","inf":"générer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je récupère","inf":"récupérer","cible":"é","niveau":"difficile"},
  {"mot":"je récupère","inf":"récupérer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je réfère","inf":"référer","cible":"é","niveau":"difficile"},
  {"mot":"je réfère","inf":"référer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je persévère","inf":"persévérer","cible":"e","niveau":"difficile"},
  {"mot":"je persévère","inf":"persévérer","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je persévère","inf":"persévérer","pos":3,"cible":"è","niveau":"difficile"},
  {"mot":"j'accélère","inf":"accélérer","cible":"é","niveau":"difficile"},
  {"mot":"j'accélère","inf":"accélérer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je préfère","inf":"préférer","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"j'élève","inf":"élever","cible":"é","niveau":"difficile"},
  {"mot":"j'élève","inf":"élever","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"ils épellent","inf":"épeler","cible":"é","niveau":"difficile"},
  {"mot":"ils épellent","inf":"épeler","pos":2,"cible":"e","altRad":"épèlent","niveau":"difficile"},

  {"mot":"nous acquérons","inf":"acquérir","cible":"é","niveau":"facile"},
  {"mot":"nous conquérons","inf":"conquérir","cible":"é","niveau":"facile"},
  {"mot":"nous requérons","inf":"requérir","cible":"é","niveau":"facile"},
  {"mot":"je réadmets","inf":"réadmettre","cible":"é","niveau":"facile"},
  {"mot":"je réduis","inf":"réduire","cible":"é","niveau":"facile"},
  {"mot":"je résous","inf":"résoudre","cible":"é","niveau":"facile"},
  {"mot":"nous nous enquérons","inf":"s'enquérir","cible":"é","niveau":"facile"},
  {"mot":"je m'écrie","inf":"s'écrier","cible":"é","niveau":"facile"},
  {"mot":"je m'éprends","inf":"s'éprendre","cible":"é","niveau":"facile"},
  {"mot":"je m'étends","inf":"s'étendre","cible":"é","niveau":"facile"},
  {"mot":"je me débats","inf":"se débattre","cible":"é","niveau":"facile"},
  {"mot":"je me découds","inf":"se découdre","cible":"é","niveau":"facile"},
  {"mot":"je me défends","inf":"se défendre","cible":"é","niveau":"facile"},
  {"mot":"je me démets","inf":"se démettre","cible":"é","niveau":"facile"},
  {"mot":"je me détends","inf":"se détendre","cible":"é","niveau":"facile"},
  {"mot":"je me dévoue","inf":"se dévouer","cible":"é","niveau":"facile"},
  {"mot":"je me méfie","inf":"se méfier","cible":"é","niveau":"facile"},
  {"mot":"je me méprends","inf":"se méprendre","cible":"é","niveau":"facile"},
  {"mot":"je me réfugie","inf":"se réfugier","cible":"é","niveau":"facile"},
  {"mot":"je me réjouis","inf":"se réjouir","cible":"é","niveau":"facile"},
  {"mot":"je me réponds","inf":"se répondre","cible":"é","niveau":"facile"},
  {"mot":"j'écris","inf":"écrire","cible":"é","niveau":"facile"},
  {"mot":"j'émeus","inf":"émouvoir","cible":"é","niveau":"facile"},
  {"mot":"je réécris","inf":"réécrire","pos":1,"cible":"é","niveau":"difficile"},
  {"mot":"je réécris","inf":"réécrire","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je réélis","inf":"réélire","pos":1,"cible":"é","niveau":"difficile"},
  {"mot":"je réélis","inf":"réélire","pos":2,"cible":"é","niveau":"difficile"},
];