// ============================================================
// BDD ACCENTS — verbes uniquement (é, è, ê, e sonnant [ɛ])
// niveau : facile (1 position testee) / difficile (2+ positions)
// deduplique : les entrees ciblant deux fois la meme lettre ont ete fusionnees
// ============================================================
const verbesAccents = [
  {"mot":"préféré","cible":"é","niveau":"difficile"},
  {"mot":"préféré","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"préféré","pos":3,"cible":"é","niveau":"difficile"},
  {"mot":"ça m'intéresse","pos":1,"cible":"é","niveau":"difficile"},
  {"mot":"ça m'intéresse","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"ça m'étonne","cible":"é","niveau":"facile"},
  {"mot":"je répare","cible":"é","niveau":"facile"},
  {"mot":"elle présente","cible":"é","niveau":"facile"},
  {"mot":"tu t'égares","cible":"é","niveau":"facile"},
  {"mot":"il se décourage","cible":"é","niveau":"facile"},
  {"mot":"je stupéfie","cible":"é","niveau":"facile"},
  {"mot":"j'appréhende","cible":"é","niveau":"facile"},
  {"mot":"je me réveille","cible":"é","niveau":"facile"},
  {"mot":"je réfléchis","cible":"é","niveau":"difficile"},
  {"mot":"je réfléchis","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je réussis","cible":"é","niveau":"facile"},
  {"mot":"elle représente","pos":2,"cible":"é","niveau":"facile"},
  {"mot":"je vécus","cible":"é","niveau":"facile"},
  {"mot":"tu régules","cible":"é","niveau":"facile"},
  {"mot":"je préfère","cible":"é","niveau":"difficile"},
  {"mot":"elle étincelle","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"j'apprécie","cible":"é","niveau":"facile"},
  {"mot":"j'atténue","cible":"é","niveau":"facile"},
  {"mot":"je bégaie","cible":"é","altRad":"bégaye","niveau":"facile"},
  {"mot":"je bénéficie","cible":"é","niveau":"difficile"},
  {"mot":"je bénéficie","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je différencie","cible":"é","niveau":"facile"},
  {"mot":"je déblaie","cible":"é","altRad":"déblaye","niveau":"facile"},
  {"mot":"je défraie","cible":"é","altRad":"défraye","niveau":"facile"},
  {"mot":"je délaie","cible":"é","altRad":"délaye","niveau":"facile"},
  {"mot":"j'égaie","cible":"é","altRad":"égaye","niveau":"facile"},
  {"mot":"j'étaie","cible":"é","altRad":"étaye","niveau":"facile"},
  {"mot":"je décrie","cible":"é","niveau":"facile"},
  {"mot":"je défie","cible":"é","niveau":"facile"},
  {"mot":"je délie","cible":"é","niveau":"facile"},
  {"mot":"je dénie","cible":"é","niveau":"facile"},
  {"mot":"je dénoue","cible":"é","niveau":"facile"},
  {"mot":"je déplie","cible":"é","niveau":"facile"},
  {"mot":"je déploie","cible":"é","niveau":"facile"},
  {"mot":"j'expédie","cible":"é","niveau":"facile"},
  {"mot":"j'éberlue","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"j'épie","cible":"é","niveau":"facile"},
  {"mot":"j'éternue","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"j'étudie","cible":"é","niveau":"facile"},
  {"mot":"j'évacue","cible":"é","niveau":"facile"},
  {"mot":"j'évalue","cible":"é","niveau":"facile"},
  {"mot":"j'évolue","cible":"é","niveau":"facile"},
  {"mot":"je maugrée","cible":"é","info":"conserve l'accent aigu du radical.","niveau":"facile"},
  {"mot":"je négocie","cible":"é","niveau":"facile"},
  {"mot":"je privilégie","cible":"é","niveau":"facile"},
  {"mot":"je recrée","pos":2,"cible":"é","info":"conserve l'accent aigu du radical.","niveau":"facile"},
  {"mot":"je crée","cible":"é","info":"conserve l'accent aigu du radical.","niveau":"facile"},
  {"mot":"je remédie","cible":"é","niveau":"facile"},
  {"mot":"je réconcilie","pos":2,"cible":"é","niveau":"facile"},
  {"mot":"je répertorie","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je résilie","cible":"é","niveau":"facile"},
  {"mot":"je spécifie","cible":"é","niveau":"facile"},
  {"mot":"je supplée","cible":"é","niveau":"facile"},
  {"mot":"je vérifie","cible":"é","niveau":"facile"},
  {"mot":"j'obéis","cible":"é","niveau":"facile"},
  {"mot":"je guéris","cible":"é","niveau":"facile"},
  {"mot":"j'établis","cible":"é","niveau":"facile"},
  {"mot":"je réagis","cible":"é","niveau":"facile"},
  {"mot":"je réunis","cible":"é","niveau":"facile"},
  {"mot":"j'élargis","cible":"é","niveau":"facile"},
  {"mot":"je gémis","cible":"é","niveau":"facile"},
  {"mot":"j'anéantis","cible":"é","niveau":"facile"},
  {"mot":"je définis","cible":"é","niveau":"facile"},
  {"mot":"je démolis","cible":"é","niveau":"facile"},
  {"mot":"je désobéis","pos":2,"cible":"é","niveau":"facile"},
  {"mot":"j'éblouis","cible":"é","niveau":"facile"},
  {"mot":"j'étourdis","cible":"é","niveau":"facile"},
  {"mot":"je frémis","cible":"é","niveau":"facile"},
  {"mot":"je réjouis","cible":"é","niveau":"facile"},
  {"mot":"je rétablis","cible":"é","niveau":"facile"},
  {"mot":"je rétrécis","cible":"é","niveau":"facile"},
  {"mot":"je dépéris","cible":"é","niveau":"difficile"},
  {"mot":"je dépéris","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"j'épaissis","cible":"é","niveau":"facile"},
  {"mot":"j'épanouis","cible":"é","niveau":"facile"},
  {"mot":"je flétris","cible":"é","niveau":"facile"},
  {"mot":"je découds","cible":"é","niveau":"facile"},
  {"mot":"je défends","cible":"é","niveau":"facile"},
  {"mot":"je démords","cible":"é","niveau":"facile"},
  {"mot":"je désapprends","cible":"é","niveau":"facile"},
  {"mot":"je détends","cible":"é","niveau":"facile"},
  {"mot":"je détords","cible":"é","niveau":"facile"},
  {"mot":"j'épands","cible":"é","niveau":"facile"},
  {"mot":"j'étends","cible":"é","niveau":"facile"},
  {"mot":"je prétends","cible":"é","niveau":"facile"},
  {"mot":"je réapprends","cible":"é","niveau":"facile"},
  {"mot":"je réentends","cible":"é","niveau":"facile"},
  {"mot":"je répands","cible":"é","niveau":"facile"},
  {"mot":"je réponds","cible":"é","niveau":"facile"},
  {"mot":"je débats","cible":"é","niveau":"facile"},
  {"mot":"je démets","cible":"é","niveau":"facile"},
  {"mot":"j'émets","cible":"é","niveau":"facile"},
  {"mot":"je télétransmets","cible":"é","niveau":"difficile"},
  {"mot":"je télétransmets","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je décris","cible":"é","niveau":"facile"},
  {"mot":"je déduis","cible":"é","niveau":"facile"},
  {"mot":"je défais","cible":"é","niveau":"facile"},
  {"mot":"je démens","cible":"é","niveau":"facile"},
  {"mot":"je dépeins","cible":"é","niveau":"facile"},
  {"mot":"je déteins","cible":"é","niveau":"facile"},
  {"mot":"je détiens","cible":"é","niveau":"facile"},
  {"mot":"je détruis","cible":"é","niveau":"facile"},
  {"mot":"je méconnais","cible":"é","niveau":"facile"},
  {"mot":"je déplais","cible":"é","niveau":"facile"},
  {"mot":"je préviens","cible":"é","niveau":"facile"},
  {"mot":"je prévois","cible":"é","niveau":"facile"},
  {"mot":"je réapparais","cible":"é","niveau":"facile"},
  {"mot":"elle réapparaît","cible":"é","niveau":"facile"},
  {"mot":"je récris","cible":"é","niveau":"facile"},
  {"mot":"je réinscris","cible":"é","niveau":"facile"},
  {"mot":"je réintroduis","cible":"é","niveau":"facile"},
  {"mot":"je séduis","cible":"é","niveau":"facile"},
  {"mot":"elle considère","cible":"è","niveau":"facile"},
  {"mot":"elle digère","cible":"è","niveau":"facile"},
  {"mot":"je modèle","cible":"è","niveau":"facile"},
  {"mot":"j'achète","cible":"è","niveau":"facile"},
  {"mot":"je gèle","cible":"è","niveau":"facile"},
  {"mot":"je lève","cible":"è","niveau":"facile"},
  {"mot":"je pèse","cible":"è","niveau":"facile"},
  {"mot":"je libère","cible":"è","niveau":"facile"},
  {"mot":"je tolère","cible":"è","niveau":"facile"},
  {"mot":"je modère","cible":"è","niveau":"facile"},
  {"mot":"je coopère","cible":"è","niveau":"facile"},
  {"mot":"j'adhère","cible":"è","niveau":"facile"},
  {"mot":"je transfère","cible":"è","niveau":"facile"},
  {"mot":"je prolifère","cible":"è","niveau":"facile"},
  {"mot":"je diffère","cible":"è","niveau":"facile"},
  {"mot":"j'opère","cible":"è","niveau":"facile"},
  {"mot":"j'altère","cible":"è","niveau":"facile"},
  {"mot":"je cède","cible":"è","niveau":"facile"},
  {"mot":"je possède","cible":"è","niveau":"facile"},
  {"mot":"je succède","cible":"è","niveau":"facile"},
  {"mot":"je procède","cible":"è","niveau":"facile"},
  {"mot":"je concède","cible":"è","niveau":"facile"},
  {"mot":"je complète","cible":"è","niveau":"facile"},
  {"mot":"j'interprète","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je protège","cible":"è","niveau":"facile"},
  {"mot":"j'abrège","cible":"è","niveau":"facile"},
  {"mot":"j'assiège","cible":"è","niveau":"facile"},
  {"mot":"tu craquèles","cible":"è","altRad":"craquelles","niveau":"facile"},
  {"mot":"je ficèle","cible":"è","altRad":"ficelle","niveau":"facile"},
  {"mot":"il ficèle","cible":"è","altRad":"ficelle","niveau":"facile"},
  {"mot":"tu harcèles","cible":"è","altRad":"harcelles","niveau":"facile"},
  {"mot":"on jumèle","cible":"è","altRad":"jumelle","niveau":"facile"},
  {"mot":"tu craquèleras","cible":"è","altRad":"craquelleras","niveau":"facile"},
  {"mot":"il débossèlera","cible":"è","altRad":"débossellera","niveau":"difficile"},
  {"mot":"ils épèleront","cible":"è","altRad":"épelleront","niveau":"facile"},
  {"mot":"nous ficèlerons","cible":"è","altRad":"ficellerons","niveau":"facile"},
  {"mot":"vous harcèlerez","cible":"è","altRad":"harcellerez","niveau":"facile"},
  {"mot":"nous jumèlerons","cible":"è","altRad":"jumellerons","niveau":"facile"},
  {"mot":"je protègerai","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je tolèrerai","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je coopèrerai","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"j'exagèrerai","pos":2,"cible":"è","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"j'opèrerai","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je cèderai","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je possèderai","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je procèderai","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je succèderai","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"je complèterai","cible":"è","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"j'espère","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"j'interfère","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je chancèle","cible":"è","altRad":"chancelle","niveau":"facile"},
  {"mot":"je chancèlerai","cible":"è","altRad":"chancellerai","niveau":"facile"},
  {"mot":"j'arrête","cible":"ê","info":"de la famille d'arrestation","niveau":"facile"},
  {"mot":"je m'entête","pos":2,"cible":"ê","info":"vient du latin testa","niveau":"facile"},
  {"mot":"elle fête","cible":"ê","info":"de la famille de festif","niveau":"facile"},
  {"mot":"être","cible":"ê","info":"de la famille de je suis, nous sommes, elles sont","niveau":"facile"},
  {"mot":"tu rêves","cible":"ê","niveau":"facile"},
  {"mot":"tu m'embêtes","pos":2,"cible":"ê","info":"de la famille de bestial, bestiaux","niveau":"facile"},
  {"mot":"il se défenêtre","pos":1,"cible":"é","niveau":"difficile"},
  {"mot":"il se défenêtre","pos":3,"cible":"ê","info":"de la famille de défenestrer","niveau":"difficile"},
  {"mot":"elle tempête","pos":2,"cible":"ê","info":"de la famille de tempest en anglais","niveau":"facile"},
  {"mot":"il crêpe","cible":"ê","info":"vient du latin crispus","niveau":"facile"},
  {"mot":"fier","cible":"e","niveau":"difficile"},
  {"mot":"la mer","cible":"e","niveau":"difficile"},
  {"mot":"le fer","cible":"e","niveau":"difficile"},
  {"mot":"le ver","cible":"e","niveau":"difficile"},
  {"mot":"un hiver","cible":"e","niveau":"difficile"},
  {"mot":"un enfer","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"un répertoire","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"les miennes","cible":"e","niveau":"difficile"},
  {"mot":"les tiennes","cible":"e","niveau":"difficile"},
  {"mot":"les siennes","cible":"e","niveau":"difficile"},
  {"mot":"tellement","cible":"e","niveau":"difficile"},
  {"mot":"une étincelle","cible":"e","niveau":"difficile"},
  {"mot":"une ficelle","cible":"e","niveau":"difficile"},
  {"mot":"elles viennent","cible":"e","niveau":"difficile"},
  {"mot":"elles parviennent","cible":"e","niveau":"difficile"},
  {"mot":"elles reviennent","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"elles tiennent","cible":"e","niveau":"difficile"},
  {"mot":"elles retiennent","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"elles détiennent","cible":"e","niveau":"difficile"},
  {"mot":"elles comprennent","cible":"e","niveau":"difficile"},
  {"mot":"elles reprennent","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"elles apprennent","cible":"e","niveau":"difficile"},
  {"mot":"j'interprète","cible":"e","niveau":"difficile"},
  {"mot":"j'appelle","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je rappelle","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"j'interpelle","cible":"e","niveau":"difficile"},
  {"mot":"j'interpelle","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je rejette","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je projette","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"intéressant","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"je jette","cible":"e","niveau":"difficile"},
  {"mot":"je projette","cible":"e","niveau":"difficile"},
  {"mot":"une bergère","cible":"e","niveau":"difficile"},
  {"mot":"j'espère","cible":"e","niveau":"difficile"},
  {"mot":"j'interfère","cible":"e","niveau":"difficile"},
  {"mot":"un désert","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"un étincellement","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"un amoncellement","cible":"e","niveau":"difficile"},
  {"mot":"un dénivellement","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"un ensorcellement","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"un grommellement","cible":"e","niveau":"difficile"},
  {"mot":"un morcellement","cible":"e","niveau":"difficile"},
  {"mot":"un renouvellement","pos":2,"cible":"e","niveau":"difficile"},
  {"mot":"un ruissellement","cible":"e","niveau":"difficile"},
  {"mot":"j'exagèrerai","cible":"e","altRad":"exagérerai","niveau":"difficile"},
  {"mot":"une expérience","cible":"e","niveau":"difficile"},
  {"mot":"j'appelle","cible":"e","niveau":"difficile"},
  {"mot":"je rappelle","cible":"e","niveau":"difficile"},
  {"mot":"je persévèrerai","cible":"e","altRad":"persévérerai","niveau":"difficile"},
  {"mot":"je persévèrerai","pos":2,"cible":"é","altRad":"persévérerai","niveau":"difficile"},
  {"mot":"je persévèrerai","pos":3,"cible":"è","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je préférerai","cible":"é","altRad":"préfèrerai","niveau":"difficile"},
  {"mot":"je préférerai","pos":2,"cible":"é","altRad":"préfèrerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"j'accélèrerai","cible":"é","altRad":"accélérerai","niveau":"difficile"},
  {"mot":"j'accélèrerai","pos":2,"cible":"è","altRad":"accélérerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je récupèrerai","cible":"é","altRad":"récupérerai","niveau":"difficile"},
  {"mot":"je récupèrerai","pos":2,"cible":"è","altRad":"récupérerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je génèrerai","cible":"é","altRad":"générerai","niveau":"difficile"},
  {"mot":"je génèrerai","pos":2,"cible":"è","altRad":"générerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je répèterai","cible":"é","altRad":"répéterai","niveau":"difficile"},
  {"mot":"je répèterai","pos":2,"cible":"è","altRad":"répéterai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je réfèrerai","cible":"é","altRad":"référerai","niveau":"difficile"},
  {"mot":"je réfèrerai","pos":2,"cible":"è","altRad":"référerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je pénétrerai","cible":"é","altRad":"pénètrerai","niveau":"difficile"},
  {"mot":"je pénétrerai","pos":2,"cible":"é","altRad":"pénètrerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"je déléguerai","cible":"é","altRad":"délèguerai","niveau":"difficile"},
  {"mot":"je déléguerai","pos":2,"cible":"é","altRad":"délèguerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"j'interprèterai","cible":"e","altRad":"interpréterai","niveau":"difficile"},
  {"mot":"j'interprèterai","pos":2,"cible":"è","altRad":"interpréterai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"j'espèrerai","cible":"e","altRad":"espérerai","niveau":"difficile"},
  {"mot":"j'espèrerai","pos":2,"cible":"è","altRad":"espérerai","altCible":"é","alt":true,"niveau":"difficile"},
  {"mot":"je libèrerai","cible":"è","altRad":"libérerai","altCible":"é","alt":true,"niveau":"facile"},
  {"mot":"il débossèlera","cible":"é","altRad":"débossellera","niveau":"difficile"},
  {"mot":"j'accélérerai","cible":"é","altRad":"accélèrerai","niveau":"difficile"},
  {"mot":"j'accélérerai","pos":2,"cible":"é","altRad":"accélèrerai","altCible":"è","alt":true,"niveau":"difficile"},
  {"mot":"elle répète","cible":"é","niveau":"difficile"},
  {"mot":"elle répète","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je délègue","cible":"é","niveau":"difficile"},
  {"mot":"je délègue","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je génère","cible":"é","niveau":"difficile"},
  {"mot":"je génère","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je récupère","cible":"é","niveau":"difficile"},
  {"mot":"je récupère","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je réfère","cible":"é","niveau":"difficile"},
  {"mot":"je réfère","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je persévère","cible":"e","niveau":"difficile"},
  {"mot":"je persévère","pos":2,"cible":"é","niveau":"difficile"},
  {"mot":"je persévère","pos":3,"cible":"è","niveau":"difficile"},
  {"mot":"j'accélère","cible":"é","niveau":"difficile"},
  {"mot":"j'accélère","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"je préfère","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"j'élève","cible":"é","niveau":"difficile"},
  {"mot":"j'élève","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"ils épèlent","cible":"é","altRad":"épellent","niveau":"difficile"},
  {"mot":"ils épèlent","pos":2,"cible":"è","altRad":"épellent","niveau":"difficile"},
  {"mot":"régulièrement","cible":"é","niveau":"difficile"},
  {"mot":"régulièrement","pos":2,"cible":"è","niveau":"difficile"},
  {"mot":"un répertoire","cible":"é","niveau":"difficile"},
];
