// ============================================================
// BDD ACCENTS — é, è, ê, et son [ɛ] écrit -e (η)
// ============================================================
const verbesAccents2 = [

  // ============================================================
  // JEUX 2 et 3. Formes écrites
  // ============================================================

  // ========================================================
  // 2a. ACCENT AIGU — é (180 entrées)
  // ========================================================
   {"mot":"un éléphant","pos":1,"cible":"é"},
{"mot":"un éléphant","pos":2,"cible":"é"},
 {"mot":"préféré","pos":1,"cible":"é"},
{"mot":"préféré","pos":2,"cible":"é"},
{"mot":"préféré","pos":3,"cible":"é"},
  {"mot":"intéressant","cible":"é"},
  {"mot":"un désert","cible":"é"},
  {"mot":"les étoiles","cible":"é"},
  {"mot":"un étonnement","cible":"é"},
  {"mot":"la géographie","cible":"é"},
  {"mot":"un métier","cible":"é"},
  {"mot":"un bélier","cible":"é"},
  {"mot":"un mécanicien","cible":"é"},
  {"mot":"une réparation","cible":"é"},
  {"mot":"l'intérieur","cible":"é"},
  {"mot":"une expérience","cible":"é","pos":2},
  {"mot":"une présence","cible":"é"},
  {"mot":"un trésor","cible":"é"},
  {"mot":"la mélancolie","cible":"é"},
 {"mot":"égaré","cible":"é"},
  {"mot":"découragé","cible":"é"},
  {"mot":"stupéfait","cible":"é"},
  {"mot":"compréhensif","cible":"é"},
  {"mot":"sérieuse","cible":"é"},
  {"mot":"véritablement","cible":"é"},
  {"mot":"je me réveille","cible":"é"},
 {"mot":"je réfléchis","pos":1,"cible":"é"},
{"mot":"je réfléchis","pos":2,"cible":"é"},
  {"mot":"je réussis","cible":"é"},
{"mot":"elle représente","pos":2,"cible":"é"},
  {"mot":"je vécus","cible":"é"},
  {"mot":"léger","cible":"é"},
{"mot":"régulièrement","cible":"é","pos":1},
 {"mot":"je préfère","cible":"é"},
 {"mot":"un étincellement","cible":"é"},
  {"mot":"j'apprécie","cible":"é"},
  {"mot":"j'atténue","cible":"é"},
  {"mot":"je bégaie","altRad":"bégaye","cible":"é"},
{"mot":"je bénéficie","cible":"é"},
{"mot":"je bénéficie","pos":2,"cible":"é"},
  {"mot":"je différencie","cible":"é"},
{"mot":"je déblaie","altRad":"déblaye","cible":"é"},
{"mot":"je défraie","altRad":"défraye","cible":"é"},
{"mot":"je délaie","altRad":"délaye","cible":"é"},
{"mot":"j'égaie","altRad":"égaye","cible":"é"},
{"mot":"j'étaie","altRad":"étaye","cible":"é"},
  {"mot":"je décrie","cible":"é"},
  {"mot":"je défie","cible":"é"},
  {"mot":"je délie","cible":"é"},
  {"mot":"je dénie","cible":"é"},
  {"mot":"je dénoue","cible":"é"},
  {"mot":"je déplie","cible":"é"},
  {"mot":"je déploie","cible":"é"},
  {"mot":"j'expédie","cible":"é"},
  {"mot":"j'éberlue","cible":"é"},
  {"mot":"j'épie","cible":"é"},
  {"mot":"j'éternue","cible":"é"},
  {"mot":"j'étudie","cible":"é"},
  {"mot":"j'évacue","cible":"é"},
  {"mot":"j'évalue","cible":"é"},
  {"mot":"j'évolue","cible":"é"},
  {"mot":"je maugrée","cible":"é","info":"conserve l'accent aigu du radical."},
  {"mot":"je négocie","cible":"é"},
  {"mot":"je privilégie","cible":"é"},
  {"mot":"je recrée","cible":"é","pos":2,"info":"conserve l'accent aigu du radical."},
 {"mot":"je crée","cible":"é", "info":"conserve l'accent aigu du radical."},
  {"mot":"je remédie","cible":"é"},
  {"mot":"je réconcilie","cible":"é","pos":2},
  {"mot":"je répertorie","cible":"é"},
  {"mot":"je résilie","cible":"é"},
  {"mot":"je spécifie","cible":"é"},
  {"mot":"je stupéfie","cible":"é"},
  {"mot":"je supplée","cible":"é"},
  {"mot":"je vérifie","cible":"é"},
  {"mot":"je réussis","cible":"é"},
  {"mot":"j'obéis","cible":"é"},
  {"mot":"je guéris","cible":"é"},
  {"mot":"je réfléchis","cible":"é"},
{"mot":"je réfléchis","cible":"é","pos":2},
  {"mot":"j'établis","cible":"é"},
  {"mot":"je réagis","cible":"é"},
  {"mot":"je réunis","cible":"é"},
  {"mot":"j'élargis","cible":"é"},
  {"mot":"je gémis","cible":"é"},
  {"mot":"j'anéantis","cible":"é"},
  {"mot":"je définis","cible":"é"},
  {"mot":"je démolis","cible":"é"},
  {"mot":"je désobéis","cible":"é"},
{"mot":"je désobéis","cible":"é","pos":2},
  {"mot":"j'éblouis","cible":"é"},
  {"mot":"j'étourdis","cible":"é"},
  {"mot":"je frémis","cible":"é"},
  {"mot":"je réjouis","cible":"é"},
  {"mot":"je rétablis","cible":"é"},
  {"mot":"je rétrécis","cible":"é",},
 {"mot":"je dépéris","cible":"é"},
  {"mot":"je dépéris","cible":"é","pos":2},
  {"mot":"j'épaissis","cible":"é"},
  {"mot":"j'épanouis","cible":"é"},
  {"mot":"je flétris","cible":"é"},
  {"mot":"je découds","cible":"é"},
  {"mot":"je défends","cible":"é"},
  {"mot":"je démords","cible":"é"},
  {"mot":"je désapprends","cible":"é"},
  {"mot":"je détends","cible":"é"},
  {"mot":"je détords","cible":"é"},
  {"mot":"j'épands","cible":"é"},
  {"mot":"j'étends","cible":"é"},
  {"mot":"je prétends","cible":"é"},
  {"mot":"je réapprends","cible":"é"},
  {"mot":"je réentends","cible":"é"},
  {"mot":"je répands","cible":"é"},
  {"mot":"je réponds","cible":"é"},
  {"mot":"je débats","cible":"é"},
  {"mot":"je démets","cible":"é"},
  {"mot":"j'émets","cible":"é"},
  {"mot":"je télétransmets","cible":"é"},
 {"mot":"je télétransmets","cible":"é","pos":2},
  {"mot":"je décris","cible":"é"},
  {"mot":"je déduis","cible":"é"},
  {"mot":"je défais","cible":"é"},
  {"mot":"je démens","cible":"é"},
  {"mot":"je dépeins","cible":"é"},
  {"mot":"je déteins","cible":"é"},
  {"mot":"je détiens","cible":"é"},
  {"mot":"je détruis","cible":"é"},
  {"mot":"je méconnais","cible":"é"},
  {"mot":"je déplais","cible":"é"},
  {"mot":"je préviens","cible":"é"},
  {"mot":"je prévois","cible":"é"},
  {"mot":"je réapparais","cible":"é"},
  {"mot":"elle réapparaît","cible":"é"},
  {"mot":"je récris","cible":"é"},
  {"mot":"je réinscris","cible":"é"},
  {"mot":"je réintroduis","cible":"é"},
  {"mot":"je séduis","cible":"é"},
  {"mot":"elle représente","cible":"é","pos":2},

  // ========================================================
  // 2b. ACCENT GRAVE — è (134 entrées dont 19 alt:true)
  // ========================================================
  {"mot":"elle considère","cible":"è"},
  {"mot":"elle digère","cible":"è"},
  {"mot":"une carrière","cible":"è"},
  {"mot":"un modèle","cible":"è"},
  {"mot":"un mystère","cible":"è"},
  {"mot":"entière","cible":"è"},
  {"mot":"une planète","cible":"è"},
  {"mot":"la première","cible":"è","pos":2},
  {"mot":"légère","cible":"è","pos":2},
  {"mot":"deuxième","cible":"è","pos":2},
  {"mot":"troisième","cible":"è"},
  {"mot":"cinquième","cible":"è"},
  {"mot":"sixième","cible":"è"},
  {"mot":"septième","cible":"è","pos":2},
  {"mot":"huitième","cible":"è"},
  {"mot":"neuvième","cible":"è","pos":2},
  {"mot":"dixième","cible":"è"},
  {"mot":"vingtième","cible":"è"},
  {"mot":"centième","cible":"è","pos":2},
  {"mot":"j'achète","cible":"è"},
  {"mot":"je gèle","cible":"è"},
  {"mot":"je lève","cible":"è"},
  {"mot":"je pèse","cible":"è"},
  {"mot":"je libère","cible":"è"},
  {"mot":"je tolère","cible":"è"},
  {"mot":"je modère","cible":"è"},
  {"mot":"je coopère","cible":"è"},
  {"mot":"j'adhère","cible":"è"},
  {"mot":"je transfère","cible":"è"},
  {"mot":"je prolifère","cible":"è"},
  {"mot":"je diffère","cible":"è"},
  {"mot":"j'opère","cible":"è"},
  {"mot":"j'altère","cible":"è"},
  {"mot":"je cède","cible":"è"},
  {"mot":"je possède","cible":"è"},
  {"mot":"je succède","cible":"è"},
  {"mot":"je procède","cible":"è"},
  {"mot":"je concède","cible":"è"},
  {"mot":"je complète","cible":"è"},
  {"mot":"j'interprète","cible":"è"},
  {"mot":"je protège","cible":"è"},
  {"mot":"j'abrège","cible":"è"},
  {"mot":"j'assiège","cible":"è"},
  {"mot":"elle considère","cible":"è"},
  {"mot":"elle digère","cible":"è"},
{"mot":"tu craquèles","cible":"è","altRad":"craquelles"},
  {"mot":"je ficèle","cible":"è","altRad":"ficelle"},
  {"mot":"tu harcèles","cible":"è"},
 {"mot":"on jumèle","cible":"è","altRad":"jumelle"},
  {"mot":"tu craquèleras","cible":"è"},
  {"mot":"il débossèlera","cible":"è"},
  {"mot":"ils épèleront","cible":"è"},
  {"mot":"nous ficèlerons","cible":"è"},
  {"mot":"vous harcèlerez","cible":"è"},
  {"mot":"nous jumèlerons","cible":"è","altRad":"jumellerons"},
  {"mot":"je protègerai","cible":"è","alt":true,"altCible":"é"},
  {"mot":"je tolèrerai","cible":"è","alt":true,"altCible":"é"},
  {"mot":"je coopèrerai","cible":"è","alt":true,"altCible":"é"},
  {"mot":"j'exagèrerai","cible":"è","pos":2,"alt":true,"altCible":"é"},
  {"mot":"j'opèrerai","cible":"è","alt":true,"altCible":"é"},
  {"mot":"je cèderai","cible":"è","alt":true,"altCible":"é"},
  {"mot":"je possèderai","cible":"è","alt":true,"altCible":"é"},
  {"mot":"je procèderai","cible":"è","alt":true,"altCible":"é"},
  {"mot":"je succèderai","cible":"è","alt":true,"altCible":"é"},
  {"mot":"je complèterai","cible":"è","alt":true,"altCible":"é"},
{"mot":"j'espère","pos":2,"cible":"è"},
{"mot":"j'interfère","pos":2,"cible":"è"},
{"mot":"la pâtissière","cible":"è"},


  // ========================================================
  // 2c. ACCENT CIRCONFLEXE — ê (17 entrées)
  // ========================================================
  {"mot":"j'arrête","cible":"ê","info":"de la famille d'arrestation"},
  {"mot":"une forêt","cible":"ê","info":"de la famille de forestier"},
  {"mot":"une tête","cible":"ê","info":"vient du latin testa"},
  {"mot":"la fête","cible":"ê","info":"de la famille de festif"},
  {"mot":"être","cible":"ê","info":"de la famille de je suis, nous sommes, elles sont"},
  {"mot":"peut-être","cible":"ê","info":"vient du latin esse"},
  {"mot":"une rêverie","cible":"ê"},
  {"mot":"une bête","cible":"ê","info":"de la famille de bestial, bestiaux"},
  {"mot":"une fenêtre","cible":"ê","info":"de la famille de défenestrer"},
  {"mot":"un ancêtre","cible":"ê","info":"de la famille de ancestral"},
  {"mot":"la conquête","cible":"ê","info":"de la famille de quest en anglais"},
  {"mot":"honnête","cible":"ê","info":"de la famille de honest en anglais"},
  {"mot":"une tempête","cible":"ê","info":"de la famille de tempest en anglais"},
  {"mot":"un prêtre","cible":"ê","info":"de la famille de presbyter"},
  {"mot":"une guêpe","cible":"ê","info":"de la famille de wasp en anglais"},
  {"mot":"une crêpe","cible":"ê","info":"vient du latin crispus"},
 {"mot":"benêt","cible":"ê","info":"de la famille de Benoît, bénédictin"},

  // ========================================================
  // 2e. SON [ɛ] — ÉCRIT -e — avant R final ou double consonne (25 entrées)
  // ========================================================
{"mot":"fier","cible":"e"},
{"mot":"la mer","cible":"e"},
{"mot":"le fer","cible":"e"},
{"mot":"le ver","cible":"e"},
{"mot":"un hiver","cible":"e"},
{"mot":"un enfer","cible":"e","pos":2},
{"mot":"un répertoire","cible":"e","pos":2},
{"mot":"elle","cible":"e"},
{"mot":"cette","cible":"e"},
{"mot":"les miennes","cible":"e"},
{"mot":"les tiennes","cible":"e"},
{"mot":"les siennes","cible":"e"},
{"mot":"quelle","cible":"e"},
{"mot":"tellement","cible":"e"},
{"mot":"une étincelle","cible":"e"},
{"mot":"une ficelle","cible":"e"},
{"mot":"elles viennent","cible":"e"},
{"mot":"elles parviennent","cible":"e"},
{"mot":"elles reviennent","cible":"e"},
{"mot":"elles tiennent","cible":"e"},
{"mot":"elles retiennent","cible":"e"},
{"mot":"elles détiennent","cible":"e"},
{"mot":"elles comprennent","cible":"e"},
{"mot":"elles reprennent","cible":"e"},
{"mot":"elles apprennent","cible":"e"},
{"mot":"j'appelle","cible":"e","pos":2},
{"mot":"je rappelle","cible":"e","pos":2},
{"mot":"j'interpelle","cible":"e","pos":1},
{"mot":"j'interpelle","cible":"e","pos":2},
{"mot":"je rejette","cible":"e","pos":2},
{"mot":"je projette","cible":"e","pos":2},
{"mot":"intéressant","cible":"e","pos":2},
{"mot":"je jette","cible":"e","pos":1},
{"mot":"je rejette","cible":"e","pos":2},
{"mot":"je projette","cible":"e","pos":1},
{"mot":"une bergère","cible":"e"},
{"mot":"j'espère","pos":1,"cible":"e"},
{"mot":"j'interfère","pos":1,"cible":"e"},
 {"mot":"un désert","cible":"e","pos":2},
{"mot":"une bergère","cible":"e"},
 {"mot":"un étincellement","cible":"e","pos":2},
{"mot":"un amoncellement","cible":"e"},
 {"mot":"un dénivellement","cible":"e","pos":2},
  {"mot":"un ensorcellement","cible":"e","pos":2},
  {"mot":"un grommellement","cible":"e"},
  {"mot":"un morcellement","cible":"e"},
  {"mot":"un renouvellement","cible":"e","pos":2},
  {"mot":"un ruissellement","cible":"e"},
{"mot":"je répertorie","cible":"e","pos":2},
 {"mot":"je chancelle","cible":"e"},
 {"mot":"je chancellerai","cible":"e"},

//========================================================
  // 2f. formes complexes — multiples e qui se prononcent [ɛ] — (26 entrées)
  // ========================================================
{"mot":"je persévèrerai","pos":1,"cible":"e"},
{"mot":"je persévèrerai","pos":2,"cible":"é"},
{"mot":"je persévèrerai","pos":3,"cible":"è","alt":true,"altCible":"é"},
{"mot":"je préférerai","pos":1,"cible":"é"},
{"mot":"je préférerai","pos":2,"cible":"é","alt":true,"altCible":"è"},
{"mot":"j'accélèrerai","pos":1,"cible":"é"},
{"mot":"j'accélèrerai","pos":2,"cible":"è","alt":true,"altCible":"é"},
{"mot":"je récupèrerai","pos":1,"cible":"é"},
{"mot":"je récupèrerai","pos":2,"cible":"è","alt":true,"altCible":"é"},
{"mot":"je génèrerai","pos":1,"cible":"é"},
{"mot":"je génèrerai","pos":2,"cible":"è","alt":true,"altCible":"é"},
{"mot":"je répèterai","pos":1,"cible":"é"},
{"mot":"je répèterai","pos":2,"cible":"è","alt":true,"altCible":"é"},
{"mot":"je réfèrerai","pos":1,"cible":"é"},
{"mot":"je réfèrerai","pos":2,"cible":"è","alt":true,"altCible":"é"},
{"mot":"je pénétrerai","pos":1,"cible":"é"},
{"mot":"je pénétrerai","pos":2,"cible":"é","alt":true,"altCible":"è"},
{"mot":"je délèguerai","pos":1,"cible":"é"},
{"mot":"je déléguerai","pos":2,"cible":"é","alt":true,"altCible":"è"},
{"mot":"je génèrerai","pos":1,"cible":"é"},
{"mot":"je génèrerai","pos":2,"cible":"è","alt":true,"altCible":"é"},
{"mot":"j'interprèterai","pos":1,"cible":"e"},
{"mot":"j'interprèterai","pos":2,"cible":"è","alt":true,"altCible":"é"},
{"mot":"j'espèrerai","pos":1,"cible":"e"},
{"mot":"j'espèrerai","pos":2,"cible":"è","alt":true,"altCible":"é"},
{"mot":"je libèrerai","pos":1,"cible":"è","alt":true,"altCible":"é"},
{"mot":"elle répète","pos":1,"cible":"é"},
{"mot":"elle répète","pos":2,"cible":"è"},
{"mot":"je délègue","pos":1,"cible":"é"},
{"mot":"je délègue","pos":2,"cible":"è"},
{"mot":"je génère","pos":1,"cible":"é"},
{"mot":"je génère","pos":2,"cible":"è"},
{"mot":"je récupère","pos":1,"cible":"é"},
{"mot":"je récupère","pos":2,"cible":"è"},
{"mot":"je réfère","pos":1,"cible":"é"},
{"mot":"je réfère","pos":2,"cible":"è"},
{"mot":"je persévère","pos":1,"cible":"e"},
{"mot":"je persévère","pos":2,"cible":"é"},
{"mot":"je persévère","pos":3,"cible":"è"},
{"mot":"j'accélère","pos":1,"cible":"é"},
{"mot":"j'accélère","pos":2,"cible":"è"},
{"mot":"j'élève","pos":1,"cible":"é"},
{"mot":"j'élève","pos":2,"cible":"è"},
{"mot":"je préfère","pos":1,"cible":"é"},
{"mot":"je préfère","pos":2,"cible":"è"},
{"mot":"régulièrement","pos":1,"cible":"é"},
{"mot":"régulièrement","pos":2,"cible":"è"},
{"mot":"elle répète","pos":1,"cible":"é"},
{"mot":"elle répète","pos":2,"cible":"è"},
{"mot":"un répertoire","pos":1,"cible":"é"},
{"mot":"un répertoire","pos":2,"cible":"e"},
{"mot":"il débossèlera","cible":"é","altRad":"débossellera"},
{"mot":"il débossèlera","pos":2,"cible":"è","altRad":"débossellera"},
  {"mot":"ils épèlent","cible":"é","altRad":"épellent"},
{"mot":"ils épèlent","pos":2,"cible":"è","altRad":"épellent"},
{"mot":"j'accélérerai","cible":"é"},
{"mot":"j'accélérerai","cible":"é","pos":2},

];
