// ================================================================
// BDD PARTICIPE PASSE - JEU 1 (e / i / u)
// rad + cible reconstituent le participe passe (rad+cible)
// ex = exemple avec temps compose tournant
// niveau : facile / difficile
// ================================================================
const verbesPP_jeu1 = [
  {"inf":"aller","rad":"all","cible":"e","ex":["tu es allé - Passé composé"],"niveau":"facile"},
  {"inf":"aboyer","rad":"aboy","cible":"e","ex":["elle aura aboyé - Futur antérieur"],"niveau":"facile"},
  {"inf":"accéder","rad":"accéd","cible":"e","ex":["que vous ayez accédé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"acheter","rad":"achet","cible":"e","ex":["elles avaient acheté - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"acquiescer","rad":"acquiesc","cible":"e","ex":["tu aurais acquiescé - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"acquitter","rad":"acquitt","cible":"e","ex":["elle a acquitté - Passé composé"],"niveau":"difficile"},
  {"inf":"adhérer","rad":"adhér","cible":"e","ex":["vous aurez adhéré - Futur antérieur"],"niveau":"difficile"},
  {"inf":"appuyer","rad":"appuy","cible":"e","ex":["qu'elles aient appuyé - Subjonctif passé"],"niveau":"facile"},
  {"inf":"arriver","rad":"arriv","cible":"e","ex":["tu étais arrivé - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"avouer","rad":"avou","cible":"e","ex":["elle aurait avoué - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"balayer","rad":"balay","cible":"e","ex":["vous avez balayé - Passé composé"],"niveau":"facile"},
  {"inf":"bayer","rad":"bay","cible":"e","ex":["elles auront bayé - Futur antérieur"],"niveau":"difficile"},
  {"inf":"broyer","rad":"broy","cible":"e","ex":["que tu aies broyé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"bégayer","rad":"bégay","cible":"e","ex":["elle avait bégayé - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"bêler","rad":"bêl","cible":"e","ex":["vous auriez bêlé - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"cesser","rad":"cess","cible":"e","ex":["elles ont cessé - Passé composé"],"niveau":"facile"},
  {"inf":"chanceler","rad":"chancel","cible":"e","ex":["tu auras chancelé - Futur antérieur"],"niveau":"difficile"},
  {"inf":"chatoyer","rad":"chatoy","cible":"e","ex":["qu'elle ait chatoyé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"choyer","rad":"choy","cible":"e","ex":["vous aviez choyé - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"clignoter","rad":"clignot","cible":"e","ex":["elles auraient clignoté - Conditionnel passé"],"niveau":"facile"},
  {"inf":"convoyer","rad":"convoy","cible":"e","ex":["tu as convoyé - Passé composé"],"niveau":"difficile"},
  {"inf":"coopérer","rad":"coopér","cible":"e","ex":["elle aura coopéré - Futur antérieur"],"niveau":"facile"},
  {"inf":"coïncider","rad":"coïncid","cible":"e","ex":["que vous ayez coïncidé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"crocheter","rad":"crochet","cible":"e","ex":["elles avaient crocheté - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"côtoyer","rad":"côtoy","cible":"e","ex":["tu aurais côtoyé - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"demander","rad":"demand","cible":"e","ex":["elle a demandé - Passé composé"],"niveau":"facile"},
  {"inf":"desserrer","rad":"desserr","cible":"e","ex":["vous aurez desserré - Futur antérieur"],"niveau":"difficile"},
  {"inf":"donner","rad":"donn","cible":"e","ex":["qu'elles aient donné - Subjonctif passé"],"niveau":"facile"},
  {"inf":"déblayer","rad":"déblay","cible":"e","ex":["tu avais déblayé - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"décacheter","rad":"décachet","cible":"e","ex":["elle aurait décacheté - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"déceler","rad":"décel","cible":"e","ex":["vous avez décelé - Passé composé"],"niveau":"difficile"},
  {"inf":"décider","rad":"décid","cible":"e","ex":["elles auront décidé - Futur antérieur"],"niveau":"facile"},
  {"inf":"déficeler","rad":"déficel","cible":"e","ex":["que tu aies déficelé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"défrayer","rad":"défray","cible":"e","ex":["elle avait défrayé - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"dégeler","rad":"dégel","cible":"e","ex":["vous auriez dégelé - Conditionnel passé"],"niveau":"facile"},
  {"inf":"déjeuner","rad":"déjeun","cible":"e","ex":["elles ont déjeuné - Passé composé"],"niveau":"facile"},
  {"inf":"délayer","rad":"délay","cible":"e","ex":["tu auras délayé - Futur antérieur"],"niveau":"difficile"},
  {"inf":"déléguer","rad":"délégu","cible":"e","ex":["qu'elle ait délégué - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"démanteler","rad":"démantel","cible":"e","ex":["vous aviez démantelé - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"dénouer","rad":"dénou","cible":"e","ex":["elles auraient dénoué - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"déployer","rad":"déploy","cible":"e","ex":["tu as déployé - Passé composé"],"niveau":"difficile"},
  {"inf":"déverser","rad":"dévers","cible":"e","ex":["elle aura déversé - Futur antérieur"],"niveau":"difficile"},
  {"inf":"dévoyer","rad":"dévoy","cible":"e","ex":["que vous ayez dévoyé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"dîner","rad":"dîn","cible":"e","ex":["elles avaient dîné - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"effrayer","rad":"effray","cible":"e","ex":["tu aurais effrayé - Conditionnel passé"],"niveau":"facile"},
  {"inf":"empaqueter","rad":"empaquet","cible":"e","ex":["elle a empaqueté - Passé composé"],"niveau":"difficile"},
  {"inf":"employer","rad":"employ","cible":"e","ex":["vous aurez employé - Futur antérieur"],"niveau":"facile"},
  {"inf":"ennuyer","rad":"ennuy","cible":"e","ex":["qu'elles aient ennuyé - Subjonctif passé"],"niveau":"facile"},
  {"inf":"enrayer","rad":"enray","cible":"e","ex":["tu avais enrayé - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"entrer","rad":"entr","cible":"e","ex":["elle serait entrée - Conditionnel passé"],"niveau":"facile"},
  {"inf":"envoyer","rad":"envoy","cible":"e","ex":["vous avez envoyé - Passé composé"],"niveau":"facile"},
  {"inf":"essayer","rad":"essay","cible":"e","ex":["elles auront essayé - Futur antérieur"],"niveau":"facile"},
  {"inf":"essuyer","rad":"essuy","cible":"e","ex":["que tu aies essuyé - Subjonctif passé"],"niveau":"facile"},
  {"inf":"exhaler","rad":"exhal","cible":"e","ex":["elle avait exhalé - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"écouter","rad":"écout","cible":"e","ex":["vous auriez écouté - Conditionnel passé"],"niveau":"facile"},
  {"inf":"égayer","rad":"égay","cible":"e","ex":["elles ont égayé - Passé composé"],"niveau":"difficile"},
  {"inf":"élever","rad":"élev","cible":"e","ex":["tu auras élevé - Futur antérieur"],"niveau":"facile"},
  {"inf":"épousseter","rad":"épousset","cible":"e","ex":["qu'elle ait épousseté - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"étayer","rad":"étay","cible":"e","ex":["vous aviez étayé - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"étiqueter","rad":"étiquet","cible":"e","ex":["elles auraient étiqueté - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"festoyer","rad":"festoy","cible":"e","ex":["tu as festoyé - Passé composé"],"niveau":"difficile"},
  {"inf":"feuilleter","rad":"feuillet","cible":"e","ex":["elle aura feuilleté - Futur antérieur"],"niveau":"facile"},
  {"inf":"ficeler","rad":"ficel","cible":"e","ex":["que vous ayez ficelé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"flamboyer","rad":"flamboy","cible":"e","ex":["elles avaient flamboyé - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"foudroyer","rad":"foudroy","cible":"e","ex":["tu aurais foudroyé - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"fourvoyer","rad":"fourvoy","cible":"e","ex":["elle a fourvoyé - Passé composé"],"niveau":"difficile"},
  {"inf":"haleter","rad":"halet","cible":"e","ex":["vous aurez haleté - Futur antérieur"],"niveau":"difficile"},
  {"inf":"harceler","rad":"harcel","cible":"e","ex":["qu'elles aient harcelé - Subjonctif passé"],"niveau":"facile"},
  {"inf":"influencer","rad":"influenc","cible":"e","ex":["tu avais influencé - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"intéresser","rad":"intéress","cible":"e","ex":["elle aurait intéressé - Conditionnel passé"],"niveau":"facile"},
  {"inf":"larmoyer","rad":"larmoy","cible":"e","ex":["vous avez larmoyé - Passé composé"],"niveau":"difficile"},
  {"inf":"louer","rad":"lou","cible":"e","ex":["elles auront loué - Futur antérieur"],"niveau":"facile"},
  {"inf":"louvoyer","rad":"louvoy","cible":"e","ex":["que tu aies louvoyé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"léguer","rad":"légu","cible":"e","ex":["elle avait légué - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"maugréer","rad":"maugré","cible":"e","ex":["vous auriez maugréé - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"monnayer","rad":"monnay","cible":"e","ex":["elles ont monnayé - Passé composé"],"niveau":"difficile"},
  {"inf":"nettoyer","rad":"nettoy","cible":"e","ex":["tu auras nettoyé - Futur antérieur"],"niveau":"facile"},
  {"inf":"nier","rad":"ni","cible":"e","ex":["qu'elle ait nié - Subjonctif passé"],"niveau":"facile"},
  {"inf":"nouer","rad":"nou","cible":"e","ex":["vous aviez noué - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"noyer","rad":"noy","cible":"e","ex":["elles auraient noyé - Conditionnel passé"],"niveau":"facile"},
  {"inf":"octroyer","rad":"octroy","cible":"e","ex":["tu as octroyé - Passé composé"],"niveau":"difficile"},
  {"inf":"pagayer","rad":"pagay","cible":"e","ex":["elle aura pagayé - Futur antérieur"],"niveau":"difficile"},
  {"inf":"parsemer","rad":"parsem","cible":"e","ex":["que vous ayez parsemé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"payer","rad":"pay","cible":"e","ex":["elles avaient payé - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"ployer","rad":"ploy","cible":"e","ex":["tu aurais ployé - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"prodiguer","rad":"prodigu","cible":"e","ex":["elle a prodigué - Passé composé"],"niveau":"difficile"},
  {"inf":"profiter","rad":"profit","cible":"e","ex":["vous aurez profité - Futur antérieur"],"niveau":"facile"},
  {"inf":"projeter","rad":"projet","cible":"e","ex":["qu'elles aient projeté - Subjonctif passé"],"niveau":"facile"},
  {"inf":"rayer","rad":"ray","cible":"e","ex":["tu avais rayé - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"receler","rad":"recel","cible":"e","ex":["elle aurait recelé - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"recréer","rad":"recré","cible":"e","ex":["vous avez recréé - Passé composé"],"niveau":"difficile"},
  {"inf":"rectifier","rad":"rectifi","cible":"e","ex":["elles auront rectifié - Futur antérieur"],"niveau":"facile"},
  {"inf":"relayer","rad":"relay","cible":"e","ex":["que tu aies relayé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"reléguer","rad":"relégu","cible":"e","ex":["elle avait relégué - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"remblayer","rad":"remblay","cible":"e","ex":["vous auriez remblayé - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"rentrer","rad":"rentr","cible":"e","ex":["elles ont rentré la voiture - Passé composé", "tu seras rentré - Futur antérieur"],"niveau":"facile"},
  {"inf":"renvoyer","rad":"renvoy","cible":"e","ex":["qu'elle ait renvoyé - Subjonctif passé"],"niveau":"facile"},
  {"inf":"reprocher","rad":"reproch","cible":"e","ex":["vous aviez reproché - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"ressemeler","rad":"ressemel","cible":"e","ex":["elles auraient ressemelé - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"s'arrêter","rad":"arrêt","cible":"e","ex":["tu t'es arrêté - Passé composé"],"niveau":"facile"},
  {"inf":"se dévouer","rad":"dévou","cible":"e","ex":["elle se sera dévouée - Futur antérieur"],"niveau":"difficile"},
  {"inf":"se frayer","rad":"fray","cible":"e","ex":["que vous vous soyez frayé un chemin - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"secouer","rad":"secou","cible":"e","ex":["elles avaient secoué - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"soudoyer","rad":"soudoy","cible":"e","ex":["tu aurais soudoyé - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"souffler","rad":"souffl","cible":"e","ex":["elle a soufflé - Passé composé"],"niveau":"facile"},
  {"inf":"soupeser","rad":"soupes","cible":"e","ex":["vous aurez soupesé - Futur antérieur"],"niveau":"difficile"},
  {"inf":"succéder","rad":"succéd","cible":"e","ex":["qu'elles aient succédé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"suppléer","rad":"supplé","cible":"e","ex":["tu avais suppléé - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"surgeler","rad":"surgel","cible":"e","ex":["elle aurait surgelé - Conditionnel passé"],"niveau":"facile"},
  {"inf":"surpayer","rad":"surpay","cible":"e","ex":["vous avez surpayé - Passé composé"],"niveau":"difficile"},
  {"inf":"s’apitoyer","rad":"apitoy","cible":"e","ex":["elles se seront apitoyées - Futur antérieur"],"niveau":"difficile"},
  {"inf":"tapisser","rad":"tapiss","cible":"e","ex":["que tu aies tapissé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"tatouer","rad":"tatou","cible":"e","ex":["elle avait tatoué - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"tomber","rad":"tomb","cible":"e","ex":["vous seriez tombés - Conditionnel passé"],"niveau":"facile"},
  {"inf":"tournoyer","rad":"tournoy","cible":"e","ex":["elles ont tournoyé - Passé composé"],"niveau":"difficile"},
  {"inf":"tutoyer","rad":"tutoy","cible":"e","ex":["tu auras tutoyé - Futur antérieur"],"niveau":"facile"},
  {"inf":"verdoyer","rad":"verdoy","cible":"e","ex":["qu'elle ait verdoyé - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"vouer","rad":"vou","cible":"e","ex":["vous aviez voué - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"vouvoyer","rad":"vouvoy","cible":"e","ex":["elles auraient vouvoyé - Conditionnel passé"],"niveau":"facile"},
  {"inf":"zézayer","rad":"zézay","cible":"e","ex":["tu as zézayé - Passé composé"],"niveau":"difficile"},
  {"inf":"agir","rad":"ag","cible":"i","ex":["elle aura agi - Futur antérieur"],"niveau":"facile"},
  {"inf":"applaudir","rad":"applaud","cible":"i","ex":["que vous ayez applaudi - Subjonctif passé"],"niveau":"facile"},
  {"inf":"arrondir","rad":"arrond","cible":"i","ex":["elles avaient arrondi - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"avertir","rad":"avert","cible":"i","ex":["tu aurais averti - Conditionnel passé"],"niveau":"facile"},
  {"inf":"blanchir","rad":"blanch","cible":"i","ex":["elle a blanchi - Passé composé"],"niveau":"facile"},
  {"inf":"blondir","rad":"blond","cible":"i","ex":["vous aurez blondi - Futur antérieur"],"niveau":"difficile"},
  {"inf":"blêmir","rad":"blêm","cible":"i","ex":["qu'elles aient blêmi - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"bondir","rad":"bond","cible":"i","ex":["tu avais bondi - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"bouillir","rad":"bouill","cible":"i","ex":["elle aurait bouilli - Conditionnel passé"],"niveau":"facile"},
  {"inf":"brunir","rad":"brun","cible":"i","ex":["vous avez bruni - Passé composé"],"niveau":"facile"},
  {"inf":"bâtir","rad":"bât","cible":"i","ex":["elles auront bâti - Futur antérieur"],"niveau":"facile"},
  {"inf":"bénir","rad":"bén","cible":"i","ex":["que tu aies béni - Subjonctif passé"],"niveau":"facile"},
  {"inf":"choisir","rad":"chois","cible":"i","ex":["elle avait choisi - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"divertir","rad":"divert","cible":"i","ex":["vous auriez diverti - Conditionnel passé"],"niveau":"facile"},
  {"inf":"durcir","rad":"durc","cible":"i","ex":["elles ont durci - Passé composé"],"niveau":"facile"},
  {"inf":"définir","rad":"défin","cible":"i","ex":["tu auras défini - Futur antérieur"],"niveau":"facile"},
  {"inf":"embellir","rad":"embell","cible":"i","ex":["qu'elle ait embelli - Subjonctif passé"],"niveau":"facile"},
  {"inf":"emplir","rad":"empl","cible":"i","ex":["vous aviez empli - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"engloutir","rad":"englout","cible":"i","ex":["elles auraient englouti - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"enrichir","rad":"enrich","cible":"i","ex":["tu as enrichi - Passé composé"],"niveau":"facile"},
  {"inf":"envahir","rad":"envah","cible":"i","ex":["elle aura envahi - Futur antérieur"],"niveau":"facile"},
  {"inf":"réunir","rad":"réun","cible":"i","ex":["que vous ayez réuni - Subjonctif passé"],"niveau":"facile"},
  {"inf":"éblouir","rad":"éblou","cible":"i","ex":["elles avaient ébloui - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"éclaircir","rad":"éclairc","cible":"i","ex":["tu aurais éclairci - Conditionnel passé"],"niveau":"facile"},
  {"inf":"élargir","rad":"élarg","cible":"i","ex":["elle a élargi - Passé composé"],"niveau":"facile"},
  {"inf":"épaissir","rad":"épaiss","cible":"i","ex":["vous aurez épaissi - Futur antérieur"],"niveau":"facile"},
  {"inf":"établir","rad":"établ","cible":"i","ex":["qu'elles aient établi - Subjonctif passé"],"niveau":"facile"},
  {"inf":"attendre","rad":"attend","cible":"u","ex":["tu avais attendu - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"battre","rad":"batt","cible":"u","ex":["elle aurait battu - Conditionnel passé"],"niveau":"facile"},
  {"inf":"combattre","rad":"combatt","cible":"u","ex":["vous avez combattu - Passé composé"],"niveau":"facile"},
  {"inf":"condescendre","rad":"condescend","cible":"u","ex":["elles auront condescendu - Futur antérieur"],"niveau":"difficile"},
  {"inf":"confondre","rad":"confond","cible":"u","ex":["que tu aies confondu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"consentir","rad":"consent","cible":"i","ex":["elle avait consenti - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"correspondre","rad":"correspond","cible":"u","ex":["vous auriez correspondu - Conditionnel passé"],"niveau":"facile"},
  {"inf":"coudre","rad":"cous","cible":"u","ex":["elles ont cousu - Passé composé"],"niveau":"facile"},
  {"inf":"descendre","rad":"descend","cible":"u","ex":["tu auras descendu la poubelle - Futur antérieur", "qu'elle soit descendue - Subjonctif passé"],"niveau":"facile"},
  {"inf":"desservir","rad":"desserv","cible":"i","ex":["vous aviez desservi - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"dormir","rad":"dorm","cible":"i","ex":["elles auraient dormi - Conditionnel passé"],"niveau":"facile"},
  {"inf":"découdre","rad":"décous","cible":"u","ex":["tu as décousu - Passé composé"],"niveau":"difficile"},
  {"inf":"défendre","rad":"défend","cible":"u","ex":["elle aura défendu - Futur antérieur"],"niveau":"facile"},
  {"inf":"démentir","rad":"dément","cible":"i","ex":["que vous ayez démenti - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"démordre","rad":"démord","cible":"u","ex":["elles avaient démordu - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"départir","rad":"départ","cible":"i","ex":["tu aurais départi - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"dépendre","rad":"dépend","cible":"u","ex":["elle a dépendu - Passé composé"],"niveau":"facile"},
  {"inf":"détendre","rad":"détend","cible":"u","ex":["vous aurez détendu - Futur antérieur"],"niveau":"facile"},
  {"inf":"distendre","rad":"distend","cible":"u","ex":["qu'elles aient distendu - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"enfouir","rad":"enfou","cible":"i","ex":["tu avais enfoui - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"engourdir","rad":"engourd","cible":"i","ex":["elle aurait engourdi - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"entendre","rad":"entend","cible":"u","ex":["vous avez entendu - Passé composé"],"niveau":"facile"},
  {"inf":"fendre","rad":"fend","cible":"u","ex":["elles auront fendu - Futur antérieur"],"niveau":"difficile"},
  {"inf":"fondre","rad":"fond","cible":"u","ex":["que tu aies fondu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"fuir","rad":"fu","cible":"i","ex":["elle avait fui - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"mentir","rad":"ment","cible":"i","ex":["vous auriez menti - Conditionnel passé"],"niveau":"facile"},
  {"inf":"mordre","rad":"mord","cible":"u","ex":["elles ont mordu - Passé composé"],"niveau":"facile"},
  {"inf":"naître","rad":"n","cible":"e","ex":["tu seras né - Futur antérieur"],"niveau":"facile"},
  {"inf":"partir","rad":"part","cible":"i","ex":["qu'elle ait parti - Subjonctif passé"],"niveau":"facile"},
  {"inf":"pendre","rad":"pend","cible":"u","ex":["vous aviez pendu - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"perdre","rad":"perd","cible":"u","ex":["elles auraient perdu - Conditionnel passé"],"niveau":"facile"},
  {"inf":"pondre","rad":"pond","cible":"u","ex":["tu as pondu - Passé composé"],"niveau":"facile"},
  {"inf":"pourfendre","rad":"pourfend","cible":"u","ex":["elle aura pourfendu - Futur antérieur"],"niveau":"difficile"},
  {"inf":"pressentir","rad":"pressent","cible":"i","ex":["que vous ayez pressenti - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"prétendre","rad":"prétend","cible":"u","ex":["elles avaient prétendu - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"prévoir","rad":"prév","cible":"u","ex":["tu aurais prévu - Conditionnel passé"],"niveau":"facile"},
  {"inf":"recoudre","rad":"recous","cible":"u","ex":["elle a recousu - Passé composé"],"niveau":"difficile"},
  {"inf":"se rendormir","rad":"rendorm","cible":"i","ex":["vous vous serez rendormis - Futur antérieur"],"niveau":"facile"},
  {"inf":"rendre","rad":"rend","cible":"u","ex":["qu'elles aient rendu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"repartir","rad":"repart","cible":"i","ex":["tu avais reparti - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"ressentir","rad":"ressent","cible":"i","ex":["elle aurait ressenti - Conditionnel passé"],"niveau":"facile"},
  {"inf":"resservir","rad":"resserv","cible":"i","ex":["vous avez resservi - Passé composé"],"niveau":"difficile"},
  {"inf":"ressortir","rad":"ressort","cible":"i","ex":["elles auront ressorti - Futur antérieur"],"niveau":"facile"},
  {"inf":"revendre","rad":"revend","cible":"u","ex":["que tu aies revendu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"revoir","rad":"rev","cible":"u","ex":["elle avait revu - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"rire","rad":"r","cible":"i","ex":["vous auriez ri - Conditionnel passé"],"niveau":"facile"},
  {"inf":"répandre","rad":"répand","cible":"u","ex":["elles ont répandu - Passé composé"],"niveau":"facile"},
  {"inf":"répondre","rad":"répond","cible":"u","ex":["tu auras répondu - Futur antérieur"],"niveau":"facile"},
  {"inf":"se blottir","rad":"blott","cible":"i","ex":["qu'elle se soit blottie - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"se morfondre","rad":"morfond","cible":"u","ex":["vous vous étiez morfondus - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"se rendre","rad":"rend","cible":"u","ex":["elles se seraient rendues - Conditionnel passé"],"niveau":"facile"},
  {"inf":"se repentir","rad":"repent","cible":"i","ex":["tu t'es repenti - Passé composé"],"niveau":"difficile"},
  {"inf":"sentir","rad":"sent","cible":"i","ex":["elle aura senti - Futur antérieur"],"niveau":"facile"},
  {"inf":"servir","rad":"serv","cible":"i","ex":["que vous ayez servi - Subjonctif passé"],"niveau":"facile"},
  {"inf":"sortir","rad":"sort","cible":"i","ex":["elles avaient sorti le chien - Plus-que-parfait", "tu serais sorti - Conditionnel passé"],"niveau":"facile"},
  {"inf":"sourire","rad":"sour","cible":"i","ex":["elle a souri - Passé composé"],"niveau":"facile"},
  {"inf":"suffire","rad":"suff","cible":"i","ex":["vous aurez suffi - Futur antérieur"],"niveau":"facile"},
  {"inf":"suivre","rad":"suiv","cible":"i","ex":["qu'elles aient suivi - Subjonctif passé"],"niveau":"facile"},
  {"inf":"suspendre","rad":"suspend","cible":"u","ex":["tu avais suspendu - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"s’endormir","rad":"endorm","cible":"i","ex":["elle se serait endormie - Conditionnel passé"],"niveau":"facile"},
  {"inf":"s’enfuir","rad":"enfu","cible":"i","ex":["vous vous êtes enfuis - Passé composé"],"niveau":"facile"},
  {"inf":"s’enhardir","rad":"enhard","cible":"i","ex":["elles se seront enhardies - Futur antérieur"],"niveau":"difficile"},
  {"inf":"tendre","rad":"tend","cible":"u","ex":["que tu aies tendu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"tordre","rad":"tord","cible":"u","ex":["elle avait tordu - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"vendre","rad":"vend","cible":"u","ex":["vous auriez vendu - Conditionnel passé"],"niveau":"facile"},
  {"inf":"voir","rad":"v","cible":"u","ex":["elles ont vu - Passé composé"],"niveau":"facile"},
  {"inf":"accourir","rad":"accour","cible":"u","ex":["tu auras accouru - Futur antérieur"],"niveau":"difficile"},
  {"inf":"apercevoir","rad":"aperç","cible":"u","ex":["qu'elle ait aperçu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"apparaître","rad":"appar","cible":"u","ex":["vous aviez apparu - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"boire","rad":"b","cible":"u","ex":["elles auraient bu - Conditionnel passé"],"niveau":"facile"},
  {"inf":"comparaître","rad":"compar","cible":"u","ex":["tu as comparu - Passé composé"],"niveau":"difficile"},
  {"inf":"complaire","rad":"compl","cible":"u","ex":["elle aura complu - Futur antérieur"],"niveau":"difficile"},
  {"inf":"conclure","rad":"concl","cible":"u","ex":["que vous ayez conclu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"concourir","rad":"concour","cible":"u","ex":["elles avaient concouru - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"connaître","rad":"conn","cible":"u","ex":["tu aurais connu - Conditionnel passé"],"niveau":"facile"},
  {"inf":"courir","rad":"cour","cible":"u","ex":["elle a couru - Passé composé"],"niveau":"facile"},
  {"inf":"croire","rad":"cr","cible":"u","ex":["vous aurez cru - Futur antérieur"],"niveau":"facile"},
  {"inf":"devoir","rad":"d","cible":"u","ex":["qu'elles aient dû - Subjonctif passé"],"niveau":"facile"},
  {"inf":"discourir","rad":"discour","cible":"u","ex":["tu avais discouru - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"disparaître","rad":"dispar","cible":"u","ex":["elle aurait disparu - Conditionnel passé"],"niveau":"facile"},
  {"inf":"déplaire","rad":"dépl","cible":"u","ex":["vous avez déplu - Passé composé"],"niveau":"facile"},
  {"inf":"élire","rad":"él","cible":"u","ex":["elles auront élu - Futur antérieur"],"niveau":"facile"},
  {"inf":"réélire","rad":"réél","cible":"u","ex":["que tu aies réélu - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"émouvoir","rad":"ém","cible":"u","ex":["elle avait ému - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"promouvoir","rad":"prom","cible":"u","ex":["vous auriez promu - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"encourir","rad":"encour","cible":"u","ex":["elles ont encouru - Passé composé"],"niveau":"difficile"},
  {"inf":"lire","rad":"l","cible":"u","ex":["tu auras lu - Futur antérieur"],"niveau":"facile"},
  {"inf":"moudre","rad":"moul","cible":"u","ex":["qu'elle ait moulu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"méconnaître","rad":"méconn","cible":"u","ex":["vous aviez méconnu - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"paraître","rad":"par","cible":"u","ex":["elles auraient paru - Conditionnel passé"],"niveau":"facile"},
  {"inf":"parcourir","rad":"parcour","cible":"u","ex":["tu as parcouru - Passé composé"],"niveau":"facile"},
  {"inf":"plaire","rad":"pl","cible":"u","ex":["je lui aurai plu - Futur antérieur"],"niveau":"facile"},
  {"inf":"pourvoir","rad":"pourv","cible":"u","ex":["nous aurions pourvu - Conditionnel passé"],"niveau":"difficile"},
  {"inf":"pouvoir","rad":"p","cible":"u","ex":["ils ont pu - Passé composé"],"niveau":"facile"},
  {"inf":"prévaloir","rad":"préval","cible":"u","ex":["j'aurai prévalu - Futur antérieur"],"niveau":"difficile"},
  {"inf":"reconnaître","rad":"reconn","cible":"u","ex":["qu'il ait reconnu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"recourir","rad":"recour","cible":"u","ex":["nous avions recouru - Plus-que-parfait"],"niveau":"difficile"},
  {"inf":"relire","rad":"rel","cible":"u","ex":["ils auraient relu - Conditionnel passé"],"niveau":"facile"},
  {"inf":"revivre","rad":"revéc","cible":"u","ex":["j'ai revécu - Passé composé"],"niveau":"facile"},
  {"inf":"réapparaître","rad":"réappar","cible":"u","ex":["il aura réapparu - Futur antérieur"],"niveau":"facile"},
  {"inf":"résoudre","rad":"résol","cible":"u","ex":["que nous ayons résolu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"savoir","rad":"s","cible":"u","ex":["ils avaient su - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"se taire","rad":"t","cible":"u","ex":["je me serais tu - Conditionnel passé"],"niveau":"facile"},
  {"inf":"secourir","rad":"secour","cible":"u","ex":["il a secouru - Passé composé"],"niveau":"facile"},
  {"inf":"survivre","rad":"survéc","cible":"u","ex":["nous aurons survécu - Futur antérieur"],"niveau":"facile"},
  {"inf":"transparaître","rad":"transpar","cible":"u","ex":["qu'ils aient transparu - Subjonctif passé"],"niveau":"difficile"},
  {"inf":"valoir","rad":"val","cible":"u","ex":["j'avais valu - Plus-que-parfait"],"niveau":"facile"},
  {"inf":"vivre","rad":"véc","cible":"u","ex":["il aurait vécu - Conditionnel passé"],"niveau":"facile"},
  {"inf":"vouloir","rad":"voul","cible":"u","ex":["nous avons voulu - Passé composé"],"niveau":"facile"},
  {"inf":"être","rad":"ét","cible":"e","ex":["ils auront été - Futur antérieur"],"niveau":"facile"},
  {"inf":"avoir","rad":"e","cible":"u","ex":["que j'aie eu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"monter","rad":"mont","cible":"e","ex":["il avait monté les valises - Plus-que-parfait", "nous serions montés - Conditionnel passé"],"niveau":"facile"},
  {"inf":"retourner","rad":"retourn","cible":"e","ex":["ils ont retourné la carte - Passé composé", "je serai retourné - Futur antérieur"],"niveau":"facile"},
  {"inf":"pleuvoir","rad":"pl","cible":"u","ex":["qu'il ait plu - Subjonctif passé"],"niveau":"facile"},
  {"inf":"se plaire","rad":"pl","cible":"u","ex":["elle s'est plu à Paris - Passé composé"],"niveau":"facile"},
  {"inf":"exclure","rad":"excl","cible":"u","ex":["nous avions exclu - Plus-que-parfait"],"niveau":"facile"},
];