const verbesSubjPresent = [
  // REGULIER
//GROUPE 1 //
  { infinitif: "acheter", niveau: 1, radical: "achèt", radNousVous: "achet" },
  { infinitif: "arriver", niveau: 1, radical: "arriv" },
  { infinitif: "cesser", niveau: 1, radical: "cess" },
  { infinitif: "donner", niveau: 1, radical: "donn" },
  { infinitif: "entrer", niveau: 1, radical: "entr" },
  { infinitif: "appuyer", niveau: 2, radical: "appui", radNousVous: "appuy" },
  { infinitif: "essayer", niveau: 2, radical: "essai", radNousVous: "essay" },
  { infinitif: "envoyer", niveau: 2, radical: "envoi", radNousVous: "envoy" },
  { infinitif: "élever", niveau: 1, radical: "élèv", radNousVous: "élev" },
  { infinitif: "lever", niveau: 1, radical: "lèv", radNousVous: "lev" },

// HOMOPHONES //
  { infinitif: "courir", niveau: 1, radical: "cour" },
  { infinitif: "fuir", niveau: 1, radical: "fui", radNousVous: "fuy" },
  { infinitif: "voir", niveau: 1, radical: "voi" },
  { infinitif: "croire", niveau: 1, radical: "croi", radNousVous: "croy" },
  { infinitif: "rire", niveau: 1, radical: "ri" },
  { infinitif: "sourire", niveau: 1, radical: "souri" },
  { infinitif: "mourir", niveau: 1, radical: "meur", radNousVous: "mour" },
  { infinitif: "revoir", niveau: 1, radical: "revoi", radNousVous: "revoy" },
  { infinitif: "prévoir", niveau: 2, radical: "prévoi", radNousVous: "prévoy" },
  { infinitif: "acquérir", niveau: 3, radical: "acquièr", radNousVous: "acquér" },

// VERBES IRREGULIERS //
// GROUPE 2 //
  { infinitif: "finir", niveau: 1, radical: "finiss" },
  { infinitif: "choisir", niveau: 1, radical: "choisiss" },
  { infinitif: "grandir", niveau: 1, radical: "grandiss" },
  { infinitif: "réussir", niveau: 1, radical: "réussiss" },
  { infinitif: "obéir", niveau: 1, radical: "obéiss" },
  { infinitif: "punir", niveau: 1, radical: "puniss" },
  { infinitif: "agir", niveau: 1, radical: "agiss" },
  { infinitif: "guérir", niveau: 1, radical: "guériss" },
  { infinitif: "nourrir", niveau: 1, radical: "nourriss" },
  { infinitif: "réfléchir", niveau: 2, radical: "réfléchiss" },

// GROUPE 3 — verbes en -DRE
  { infinitif: "prendre", niveau: 1, radical: "prenn", radicalPluriel: "pren" },
  { infinitif: "entendre", niveau: 1, radical: "entend" },
  { infinitif: "rendre", niveau: 1, radical: "rend" },
  { infinitif: "répondre", niveau: 1, radical: "répond" },
  { infinitif: "vendre", niveau: 1, radical: "vend" },
  { infinitif: "perdre", niveau: 1, radical: "perd" },
  { infinitif: "attendre", niveau: 2, radical: "attend" },
  { infinitif: "comprendre", niveau: 2, radical: "comprenn", radicalPluriel: "compren" },
  { infinitif: "défendre", niveau: 2, radical: "défend" },
  { infinitif: "descendre", niveau: 2, radical: "descend" },

// GROUPE 3 — verbes en -TTRE
  { infinitif: "mettre", niveau: 1, radical: "mett" },
  { infinitif: "battre", niveau: 1, radical: "batt" },
  { infinitif: "émettre", niveau: 1, radical: "émett" },
  { infinitif: "promettre", niveau: 1, radical: "promett" },
  { infinitif: "soumettre", niveau: 1, radical: "soumett" },
  { infinitif: "admettre", niveau: 2, radical: "admett" },
  { infinitif: "débattre", niveau: 2, radical: "débatt" },
  { infinitif: "permettre", niveau: 2, radical: "permett" },
  { infinitif: "remettre", niveau: 2, radical: "remett" },
  { infinitif: "transmettre", niveau: 2, radical: "transmett" },

//VENIR et TENIR
  { infinitif: "venir", niveau: 1, radical: "vienn", radNousVous: "ven" },
  { infinitif: "tenir", niveau: 1, radical: "tienn", radNousVous: "ten" },
  { infinitif: "devenir", niveau: 2, radical: "devienn", radNousVous: "deven" },
  { infinitif: "revenir", niveau: 2, radical: "revienn", radNousVous: "reven" },
  { infinitif: "retenir", niveau: 2, radical: "retienn", radNousVous: "reten" },
  { infinitif: "contenir", niveau: 2, radical: "contienn", radNousVous: "conten" },
  { infinitif: "prévenir", niveau: 2, radical: "prévienn", radNousVous: "preven" },
  { infinitif: "convenir", niveau: 3, radical: "convienn", radNousVous: "conven" },
  { infinitif: "parvenir", niveau: 3, radical: "parvienn", radNousVous: "parven" },
  { infinitif: "soutenir", niveau: 3, radical: "soutienn", radNousVous: "souten" },

//VERBES en INDRE
  { infinitif: "craindre", niveau: 3, radical: "craign" },
  { infinitif: "peindre", niveau: 3, radical: "peign" },
  { infinitif: "plaindre", niveau: 3, radical: "plaign" },
  { infinitif: "rejoindre", niveau: 3, radical: "rejoign" },
  { infinitif: "déteindre", niveau: 3, radical: "déteign" },
  { infinitif: "ceindre", niveau: 4, radical: "ceign" },
  { infinitif: "contraindre", niveau: 4, radical: "contraign" },
  { infinitif: "feindre", niveau: 4, radical: "feign" },
  { infinitif: "joindre", niveau: 4, radical: "joign" },
  { infinitif: "teindre", niveau: 4, radical: "teign" },

// LES AUTRES
  { infinitif: "faire", niveau: 2, radical: "fass" },
  { infinitif: "dire", niveau: 1, radical: "dis" },
  { infinitif: "conduire", niveau: 1, radical: "conduis" },
  { infinitif: "connaître", niveau: 2, radical: "connaiss" },
  { infinitif: "construire", niveau: 2, radical: "construis" },
  { infinitif: "suivre", niveau: 1, radical: "suiv" },
  { infinitif: "vivre", niveau: 1, radical: "viv" },
  { infinitif: "sentir", niveau: 1, radical: "sent" },
  { infinitif: "servir", niveau: 1, radical: "serv" },
  { infinitif: "sortir", niveau: 1, radical: "sort" },
  { infinitif: "savoir", niveau: 2, radical: "sach" },
  { infinitif: "aller", niveau: 1, radical: "aill", radNousVous: "all" },
  { infinitif: "boire", niveau: 1, radical: "boiv", radNousVous: "buv" },
  { infinitif: "écrire", niveau: 1, radical: "écriv" },
  { infinitif: "lire", niveau: 1, radical: "lis" },
  { infinitif: "absoudre", niveau: 3, radical: "absolv" },
  { infinitif: "dissoudre", niveau: 3, radical: "dissolv" },
  { infinitif: "résoudre", niveau: 3, radical: "résolv" },
  { infinitif: "pouvoir", niveau: 4, radical: "puiss" },
  { infinitif: "vouloir", niveau: 3, radical: "veuill", radNousVous: "voul" },
  { infinitif: "valoir", niveau: 4, radical: "vaill", radNousVous: "val" },
  { infinitif: "vaincre", niveau: 4, radical: "vainqu" },
  { infinitif: "haïr", niveau: 2, radical: "haïss" },
  { infinitif: "devoir", niveau: 1, radical: "doiv", radNousVous: "dev" },
  { infinitif: "s'asseoir", niveau: 1, radical: "assoi", radAlt: "assey", radNousVous: "assoy", radNousVousAlt: "assey", pronominal: true },
  { infinitif: "se taire", niveau: 2, radical: "tais", pronominal: true },
  { infinitif: "falloir", niveau: 1, radical: "faill", sujetsPossibles: ["il"] },
  { infinitif: "pleuvoir", niveau: 1, radical: "pleuv", sujetsPossibles: ["il"] },
  { infinitif: "être", niveau: 1, radical: "soi" },
  { infinitif: "avoir", niveau: 1, radical: "ai" },

];
