const verbesImparfait1 = [
  {
    infinitif: "desserrer",
    groupe: 1,
    niveau: 2,
    radicalImp: "desserr-",
  },
  {
    infinitif: "diluer",
    groupe: 1,
    niveau: 1,
    radicalImp: "dilu-",
  },
  {
    infinitif: "distribuer",
    groupe: 1,
    niveau: 3,
    radicalImp: "distribu-",
  },
  {
    infinitif: "influer",
    groupe: 1,
    niveau: 4,
    radicalImp: "influ-",
  },
  {
    infinitif: "louer",
    groupe: 1,
    niveau: 1,
    radicalImp: "lou-",
  },
  {
    infinitif: "muer",
    groupe: 1,
    niveau: 4,
    radicalImp: "mu-",
  },
  {
    infinitif: "nouer",
    groupe: 1,
    niveau: 2,
    radicalImp: "nou-",
  },
  {
    infinitif: "polluer",
    groupe: 1,
    niveau: 2,
    radicalImp: "pollu-",
  },
  {
    infinitif: "remuer",
    groupe: 1,
    niveau: 2,
    radicalImp: "remu-",
  },
  {
    infinitif: "ruer",
    groupe: 1,
    niveau: 1,
    radicalImp: "ru-",
  },
  {
    infinitif: "se dévouer",
    groupe: 1,
    niveau: 3,
    pronominal: true,
    radicalJe: "me dévou-",
    radicalTu: "te dévou-",
    radicalIl: "se dévou-",
    radicalPluriel: "se dévou-",
  },
  {
    infinitif: "statuer",
    groupe: 1,
    niveau: 4,
    radicalImp: "statu-",
  },
  {
    infinitif: "suer",
    groupe: 1,
    niveau: 3,
    radicalImp: "su-",
  },
  {
    infinitif: "tatouer",
    groupe: 1,
    niveau: 3,
    radicalImp: "tatou-",
  },
  {
    infinitif: "vouer",
    groupe: 1,
    niveau: 3,
    radicalImp: "vou-",
  },
  {
    infinitif: "acquérir",
    groupe: 3,
    niveau: 4,
    radicalImp: "acquér-",
  },
  {
    infinitif: "dormir",
    groupe: 3,
    niveau: 1,
    radicalImp: "dorm-",
  },
  {
    infinitif: "mentir",
    groupe: 3,
    niveau: 3,
    radicalImp: "ment-",
  },
  {
    infinitif: "partir",
    groupe: 3,
    niveau: 1,
    radicalImp: "part-",
  },
  {
    infinitif: "rendre",
    groupe: 3,
    niveau: 2,
    radicalImp: "rend-",
  },
  {
    infinitif: "rire",
    groupe: 3,
    niveau: 1,
    radicalImp: "ri-",
  },
  {
    infinitif: "répondre",
    groupe: 3,
    niveau: 1,
    radicalImp: "répond-",
  },
  {
    infinitif: "se souvenir",
    groupe: 3,
    niveau: 3,
    pronominal: true,
    radicalJe: "me souven-",
    radicalTu: "te souven-",
    radicalIl: "se souven-",
    radicalPluriel: "se souven-",
  },
  {
    infinitif: "sentir",
    groupe: 3,
    niveau: 1,
    radicalImp: "sent-",
  },
  {
    infinitif: "s'endormir",
    groupe: 3,
    niveau: 3,
    pronominal: true,
    radicalJe: "m'endorm-",
    radicalTu: "t'endorm-",
    radicalIl: "s'endorm-",
    radicalPluriel: "s'endorm-",
  },
  {
    infinitif: "vendre",
    groupe: 3,
    niveau: 2,
    radicalImp: "vend-",
  },
  {
    infinitif: "vouloir",
    groupe: 3,
    niveau: 2,
    radicalImp: "voul-",
  },
];

const verbesImparfait2 = [
  {
    infinitif: "festoyer",
    groupe: 1,
    niveau: 4,
    radicalImp: "festoy-",
  },
  {
    infinitif: "lier",
    groupe: 1,
    niveau: 1,
    radicalImp: "li-",
  },
  {
    infinitif: "louvoyer",
    groupe: 1,
    niveau: 4,
    radicalImp: "louvoy-",
  },
  {
    infinitif: "se méfier",
    groupe: 1,
    niveau: 2,
    pronominal: true,
    radicalJe: "me méfi-",
    radicalTu: "te méfi-",
    radicalIl: "se méfi-",
    radicalPluriel: "se méfi-",
  },
  {
    infinitif: "trier",
    groupe: 1,
    niveau: 3,
    radicalImp: "tri-",
  },
  {
    infinitif: "agir",
    groupe: 2,
    niveau: 1,
    radicalImp: "agiss-",
  },
  {
    infinitif: "choisir",
    groupe: 2,
    niveau: 1,
    radicalImp: "choisiss-",
  },
  {
    infinitif: "finir",
    groupe: 2,
    niveau: 2,
    radicalImp: "finiss-",
  },
  {
    infinitif: "haïr",
    groupe: 2,
    niveau: 3,
    radicalImp: "haïss-",
  },
  {
    infinitif: "craindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "craign-",
  },
  {
    infinitif: "croire",
    groupe: 3,
    niveau: 2,
    radicalImp: "croy-",
  },
  {
    infinitif: "être",
    groupe: 3,
    niveau: 2,
    radicalImp: "ét-",
  },
  {
    infinitif: "faire",
    groupe: 3,
    niveau: 2,
    radicalImp: "fais-",
  },
  {
    infinitif: "peindre",
    groupe: 3,
    niveau: 4,
    radicalImp: "peign-",
  },
  {
    infinitif: "plaire",
    groupe: 3,
    niveau: 2,
    radicalImp: "plais-",
  },
  {
    infinitif: "résoudre",
    groupe: 3,
    niveau: 4,
    radicalImp: "résolv-",
  },
  {
    infinitif: "voir",
    groupe: 3,
    niveau: 2,
    radicalImp: "voy-",
  },
  {
    infinitif: "boire",
    groupe: 3,
    niveau: 3,
    radicalImp: "buv-",
  },
  {
    infinitif: "conduire",
    groupe: 3,
    niveau: 1,
    radicalImp: "conduis-",
  },
  {
    infinitif: "lire",
    groupe: 3,
    niveau: 2,
    radicalImp: "lis-",
  },
  {
    infinitif: "sourire",
    groupe: 3,
    niveau: 2,
    radicalImp: "souri-",
  },
  {
    infinitif: "se taire",
    groupe: 3,
    niveau: 3,
    pronominal: true,
    radicalJe: "me tais-",
    radicalTu: "te tais-",
    radicalIl: "se tais-",
    radicalPluriel: "se tais-",
  },
];